### ISSUE TITLE
Avoid requiring environment variables to point to dependencies

### ISSUE THREAD

**Issue by wdconinc** [eic/EICrecon#1]
The use of environment variables to point to dependency locations is not a common practice in open source projects outside of physics codes because it is unnecessary and error prone. CMake has mechanisms for pointing to specific locations if they are not following the filesystem hierarchy standard. Interoperability with other projects (and user experience in general) will be improved if we do not deviate from standard practice.

Of course, anyone can still decide individually to set up a bunch of environment variables, but it should not be a requirement.

**Comment by faustus123** [comment]
You should not interpret anything in this repository as permanent. This is bootstrapping and sandboxing. We’ll
clean it up a little later. The goal right now is to understand and overcome the big hurdles.

I'm going to leave this issue open so we are sure to revisit it when we get to that stage.

**Comment by faustus123** [comment]
I think we now have this well in hand.
