### ISSUE TITLE
Things get compiled twice

### ISSUE THREAD

**Issue by veprbl** [eic/EICrecon#1018]
E.g. in the latest build on main:

```output
[ 94%] Building CXX object src/global/reco/CMakeFiles/reco_library.dir/MatchClusters_factory.cc.o
...
[ 98%] Building CXX object src/global/reco/CMakeFiles/reco_plugin.dir/MatchClusters_factory.cc.o
```
https://github.com/eic/EICrecon/actions/runs/6280258041/job/17068294055#step:7:466

**Comment by wdconinc** [comment]
Yeah... #832 was the first attempt at fixing this, #940 fixed it for algorithms, and #1023 fixes it finally for src/global/reco and src/global/tracking.
