### ISSUE TITLE
CalorimeterHit thresholds from DSC feedback

### ISSUE THREAD

**Issue by kkauder** [eic/EICrecon#1029]
**Is your feature request related to a problem? Please describe.**
Calorimeter thresholds are currently set to 0.

**Describe the solution you'd like**
Thresholds have been compiled from DSCs. Tracker-like thresholds were updated in https://github.com/eic/EICrecon/pull/890. Now add calorimeter-like ones as well.

**Describe alternatives you've considered**
For the sake of this question, we considered thresholds in npsim but they don't properly reflect the mechanism.

**Additional context**
https://brookhavenlab.sharepoint.com/:x:/s/EICPublicSharingDocs/EaKgRMnPD4BFoKK-x05lUrQB4PiJyr8tVjc7LitCkW9khA?rtime=4c9KMpm_20g
Important, this overrules the google doc still in circulation. Not linking that one here to not add to the confusion.

**Comment by veprbl** [comment]
Duplicate of #895

**Comment by kkauder** [comment]
Thanks. I looked through the issues and didn't find it. Looking back, I think I had a brainfart and looked through the closed ones only.

**Comment by veprbl** [comment]
I didn't mean that this had to be closed. But okay, I've moved link to reference spreadsheet the caption of the other one.
