### ISSUE TITLE
Order of geometry arguments from DD4hep_service in algorithm init matters

### ISSUE THREAD

**Issue by simonge** [eic/EICrecon#1032]
A bit of a confusing bug as it relies on a number of conditions when multiple collections are output but when only writing one the argument list for initializing an algorithm e.g. FarDetectorTrackerCluster/MatrixTransferStatic needs to take:
`geoSvc->cellIDPositionConverter()` 
before 
`geoSvc->detector()`
(from the DD4hep_service)

The other ordering results in the error at the bottom here despite no changes in the code other than the order of the init arguments.

If a collection with the correct ordering is also included in the output **and** comes first alphabetically everything runs as expected.

Searching the code looks like these two algorithms are the only place this is currently used. The solution might be to remove the cellIDPositionConverter from the DD4hep_service and take it from the detector inside the algorithm as it is done everywhere else i.e.

`m_converter = std::make_shared<const dd4hep::rec::CellIDPositionConverter>(const_cast<dd4hep::Detector&>(*detector));
`
### Environment: 
On the main branch but testing using add_simple_tracker_hit_clustering branch in the eic-shell

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. Run eicrecon on the add_simple_tracker_hit_clustering branch with only `-Ppodio:output_include_collections=TaggerTrackerClusterPositions `
2. Runs ok if calling `-Ppodio:output_include_collections=TaggerTrackerClusterPositions,ForwardOffMRecParticles`
3. But not if renamed 'ForwardOffMRecParticles->ZForwardOffMRecParticles'
-----
4. Same on main branch but changing the order of MatrixTransferStatic init to
```
void eicrecon::MatrixTransferStatic::init(const dd4hep::Detector* det,
					  std::shared_ptr<const dd4hep::rec::CellIDPositionConverter> id_conv,
                                          std::shared_ptr<spdlog::logger> &logger) {
```
6. Then running with `-Ppodio:output_include_collections=ForwardOffMRecParticles`

### Expected Result: (what do you expect when you execute the steps above)
Output with the required collection.

### Actual Result: (what do you get when you execute the steps above)
```
Thread model: pthreads
140287080666816: 
       `- JSignalHandler::handle_sigsegv(int, siginfo_t*, void*) (0x7f973d29bff6)
        `- /lib/x86_64-linux-gnu/libc.so.6 (0x7f973cd7efd0)
         `- dd4hep::VolumeManager::lookupContext(unsigned long) const (0x7f973b686ee1)
          `- dd4hep::rec::CellIDPositionConverter::positionNominal(unsigned long const&) const (0x7f97393cb593)
           `- dd4hep::rec::CellIDPositionConverter::position(unsigned long const&) const (0x7f97393cb699)
            `- eicrecon::MatrixTransferStatic::produce(edm4hep::SimTrackerHitCollection const&) (0x7f973631b93f)
             `- eicrecon::MatrixTransferStatic_factoryT::Process(std::shared_ptr<JEvent const> const&) (0x7f973639476a)
              `- JMultifactoryHelperPodio<edm4eic::ReconstructedParticle>::Process(std::shared_ptr<JEvent const> const&) (0x7f973842af41)
               `- JFactory::Create(std::shared_ptr<JEvent const> const&) (0x7f973d1e8cf8)
                `- JFactoryPodioT<edm4eic::ReconstructedParticle>::Create(std::shared_ptr<JEvent const> const&) (0x7f973842afd8)
                 `- JEvent::GetCollectionBase(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const (0x7f97383ee608)
                  `- JEventProcessorPODIO::Process(std::shared_ptr<JEvent const> const&) (0x7f9735c4186f)
                   `- JEventProcessor::DoMap(std::shared_ptr<JEvent const> const&) (0x7f973d22272d)
                    `- JEventProcessorArrow::execute(JArrowMetrics&, unsigned long) (0x7f973d20a625)
                     `- JWorker::loop() (0x7f973d215437)
                      `- /lib/x86_64-linux-gnu/libstdc++.so.6 (0x7f973d01a4a3)
                       `- /lib/x86_64-linux-gnu/libc.so.6 (0x7f973cdcc044)
                        `- /lib/x86_64-linux-gnu/libc.so.6 (0x7f973ce4c5fc)
```

**Comment by wdconinc** [comment]
Cannot reproduces. I'm running inside eic-shell with a clean branch checkout of `add_simple_tracker_hit_clustering` and `epic_brycecanyon` and the output collection you indicated:
```
nightly> wdconinc@menelaos:~/git/EICrecon/.worktree/add_simple_tracker_hit_clustering$ $PWD/bin/eicrecon -Ppodio:output_file=rec_dis_18x275_minQ2=1000_brycecanyon.edm4eic.root -Ppodio:output_include_collections=TaggerTrackerClusterPositions sim_dis_18x275_minQ2=1000_brycecanyon.edm4hep.root
```
Is there something else I should be doing to reproduce this?

**Comment by simonge** [comment]
Cleverly I updated the branch with a patch to fix it after posting this so you might have to step back to the previous commit if that's not too hard, otherwise I can do that. The input file will also need some TaggerTrackerHits if testing with TaggerTrackerClusterPositions.

**Comment by wdconinc** [comment]
Can you post the commit hash link that has the issue?

**Comment by wdconinc** [comment]
I've now run with https://github.com/eic/EICrecon/pull/921/commits/1c215019ce249bc5e76d461471219d7ae276ea34, still unable to reproduce. This is with a NC DIS 18x275 minQ2=1000 events, which tends to cover all detectors with a variety of particles. Do you have an input file that I can use to reproduce this issue?

**Comment by simonge** [comment]
Perhaps easier I have made a branch `032-order-of-geometry-arguments-from-dd4hep_service-in-algorithm-init-matters` which breaks the Roman Pots and Off Momentum detectors in the same way so files with Q2>0.1 can be used.

In that branch calling eicrecon with `-Ppodio:output_include_collections=ForwardOffMRecParticles` should be broken (or is for me)

**Comment by wdconinc** [comment]
Ok, now I can reproduce a crash, finally!

**Comment by wdconinc** [comment]
This is only intermittently reproducible, depending on optimization in Release and RelWithDebInfo, but not always in Debug. With RelWithDebInfo, I get:
```
[INFO] Geometry successfully loaded.
[INFO] Status: 1 events processed  1.0 Hz (0.0 mHz avg)
[INFO] Status: 4 events processed  3.0 Hz (0.2 Hz avg)

Thread 2 "eicrecon" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdf23b6c0 (LWP 3296599)]
0x00007ffff63d5ee1 in dd4hep::VolumeManager::lookupContext(unsigned long) const () from /usr/local/lib/libDDCore.so.1.26
(gdb) bt
#0  0x00007ffff63d5ee1 in dd4hep::VolumeManager::lookupContext(unsigned long) const () from /usr/local/lib/libDDCore.so.1.26
#1  0x00007ffff4aaf593 in dd4hep::rec::CellIDPositionConverter::positionNominal(unsigned long const&) const () from /usr/local/lib/libDDRec.so.1.26
#2  0x00007ffff4aaf699 in dd4hep::rec::CellIDPositionConverter::position(unsigned long const&) const () from /usr/local/lib/libDDRec.so.1.26
#3  0x00007ffff343f638 in eicrecon::MatrixTransferStatic::produce (this=this@entry=0x555556c199e0, rawhits=...) at /usr/include/c++/12/bits/shared_ptr_base.h:1665
#4  0x00007ffff3460205 in eicrecon::MatrixTransferStatic_factoryT::Process (this=0x555556c19770, event=...)
    at /home/wdconinc/git/EICrecon/.worktree/1032-order-of-geometry-arguments-from-dd4hep_service-in-algorithm-init-matters/src/factories/fardetectors/MatrixTransferStatic_factoryT.h:59
#5  0x00007ffff7ec7cf8 in JFactory::Create(std::shared_ptr<JEvent const> const&) () from /usr/local/lib/libJANA.so
#6  0x00007ffff3c77aa9 in JFactoryPodioT<edm4eic::ReconstructedParticle>::Create (this=0x55555aa40760, event=...)
    at /opt/software/linux-debian12-x86_64_v2/gcc-12.2.0/jana2-2.1.1-txdpt66ozlvvdquuovpy44emsmsnuip4/include/JANA/Podio/JFactoryPodioT.h:161
#7  0x00007ffff3c5fa9c in JEvent::GetCollectionBase (this=0x55555a9da6a0, name=...) at /opt/software/linux-debian12-x86_64_v2/gcc-12.2.0/jana2-2.1.1-txdpt66ozlvvdquuovpy44emsmsnuip4/include/JANA/JEvent.h:454
#8  0x00007ffff3259227 in JEventProcessorPODIO::Process (this=0x5555557e5d40, event=...)
    at /home/wdconinc/git/EICrecon/.worktree/1032-order-of-geometry-arguments-from-dd4hep_service-in-algorithm-init-matters/src/services/io/podio/JEventProcessorPODIO.cc:287
#9  0x00007ffff7f0172d in JEventProcessor::DoMap(std::shared_ptr<JEvent const> const&) () from /usr/local/lib/libJANA.so
#10 0x00007ffff7ee9625 in JEventProcessorArrow::execute(JArrowMetrics&, unsigned long) () from /usr/local/lib/libJANA.so
#11 0x00007ffff7ef4437 in JWorker::loop() () from /usr/local/lib/libJANA.so
#12 0x00007ffff7cf94a3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff7aab044 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#14 0x00007ffff7b2b5fc in ?? () from /lib/x86_64-linux-gnu/libc.so.6
```
