### ISSUE TITLE
"LeakSanitizer has encountered a fatal error."

### ISSUE THREAD

**Issue by veprbl** [eic/EICrecon#1043]
### Environment: (where does this bug occur, have you tried other environments)
- On CI

### Steps to reproduce: (give a step by step account of how to trigger the bug)
sometimes fails by itself, and always in eicrecon-gun

### Expected Result: (what do you expect when you execute the steps above)
tests pass

### Actual Result: (what do you get when you execute the steps above)
https://github.com/eic/EICrecon/actions/runs/6396687029/job/17363523322?pr=1042#step:6:2220
```
[INFO] Closing Event Source for sim_e_1GeV_20GeV_craterlake.edm4hep.root
Tracer caught signal 11: addr=0x2c48 pc=0x55ea3eb1903a sp=0x7f945ce44d40
==548==LeakSanitizer has encountered a fatal error.
==548==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
==548==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
```

**Comment by wdconinc** [comment]
I've been annoyed by these too, but haven't been able to narrow down or reproduce. Seems to happen most often with clang builds of EICrecon and electron gun on craterlake, as in this case. We could disable fail-fast to verify that observation.

**Comment by wdconinc** [comment]
Also, the Internet claims the suggestion of verbosity and log_threads doesn't give any info.
