### ISSUE TITLE
Add JEventProcessorPODIO option to terminate on exception

### ISSUE THREAD

**Issue by wdconinc** [eic/EICrecon#1056]
> Maybe we could add an option to terminate on exception simply for the CI.

I was thinking in this direction as well. Essentially I was going to suggest a boolean parameter `allow_failing_collections` inside JEventProcessorPODIO that configures whether to fail on exceptions (well, rethrows the exception, and JANA2 should then fail).

_Originally posted by @wdconinc in https://github.com/eic/EICrecon/issues/1053#issuecomment-1749414429_

**Comment by veprbl** [comment]
Testing on CI is no different from testing locally. If such option is to be added, should be false by default.

**Comment by veprbl** [comment]
I think this functionality would just duplicate `podio:output_exclude_collections`. Suggest, we close.
