### ISSUE TITLE
Implement algorithm in Truth level kinematics plot

### ISSUE THREAD

**Issue by faustus123** [eic/EICrecon#112]
There is only one algorithm here: "InclusiveKinematicsTruth". See[ EICrecon issue #11](https://github.com/eic/EICrecon/issues/11).

**Comment by DraTeots** [comment]
Is it done?

**Comment by faustus123** [comment]
No. I copied over the juggler code into a branch, but never completed the work. The branch is still here:

https://github.com/eic/EICrecon/blob/davidl_truth_level_kinematics/src/algorithms/analysis/InclusiveKinematicsTruth.cpp

It is currently 686 commits behind main. An indication that is has not been the highest nail regarding reconstruction code.

I think I will close this as an issue for now. We can re-introduce it when this becomes a priority. I don't see that happening until everything else is working well.
