### ISSUE TITLE
Conflicting thresholds in LUMISPECCAL

### ISSUE THREAD

**Issue by kkauder** [eic/EICrecon#1155]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): main
- Which version (or `HEAD` for the most recent on git): HEAD
- Any specific OS or system where the issue occurs? No
- Any special versions of ROOT or Geant4? No

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1.  Run eic-recon with LUMISPECCAL included

### Expected Result: (what do you expect when you execute the steps above)
No conflict

### Actual Result: (what do you get when you execute the steps above)
Currently no conflict, but only until https://github.com/eic/EICrecon/pull/1099

@dhevang, the offending lines are
```
            .thresholdFactor = 4.0,
            .thresholdValue = 3.0,
```
At most one of these should be non-zero; the former parameter sets the threshold as a multiple of ADC sigmas, the latter is just a fixed value (which is usually preferred). I could just set them to zero, but I'f prefer if you could go through LUMISPECCAL.cc and double-check that all values, dynamic range, bit-ness etc. are okay.

**Comment by dhevang** [comment]
Done!
