### ISSUE TITLE
EICrecon does not install extensions/ headers

### ISSUE THREAD

**Issue by wdconinc** [eic/EICrecon#1157]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): main
- Which version (or `HEAD` for the most recent on git): HEAD
- Any specific OS or system where the issue occurs? eic-shell

### Steps to reproduce: (give a step by step account of how to trigger the bug)
```
$ ls /usr/local/include/extensions
/bin/ls: cannot access '/usr/local/include/extensions': No such file or directory
```

We should install all relevant headers, including those in extensions/. We already install the ones in services/, algorithms/ (where they clobber the eic/algorithms headers).

**Comment by wdconinc** [comment]
This may need some thought, e.g. do we want to install everything under /usr/local/EICrecon/ or so. But in the short term, we should probably just install the extensions directory headers into CMAKE_INSTALL_INCLUDEDIR.

**Comment by kkauder** [comment]
It's a problem with the general eicrecon installation. Installing it by hand (from drich-dev) doesn't solve it either, so some CMakeLists.txt needs fixing. I don't think I'm the best one to do this. @nathanwbrei @DraTeots @faustus123 , any advice?
