### ISSUE TITLE
Summary of changes needed for CLI options

### ISSUE THREAD

**Issue by cissieAB** [eic/EICrecon#117]
This is a guide for the WIP branch `cissie_cli`

Per requests of #90 #110, there are more changes needed for the CLI options.

### eicrecon "-h"/"-v" cleanup
Commit https://github.com/eic/EICrecon/commit/592ba613db9a6064242971a95f7a837bd6deae2f
- [x] Replace "jana" with "eicrecon" in eicrecon helper info.
- [x] Remove "-Phistsfile=file.root" in CLI option print info.
- [x] Set eicrecon version to 0.0.0 instead of jana version.

### Add CLI options to list plugins
PR  #119 
- [x] "--list_default_plugins": list the default plugins *without running*
- [x] "--list_available_plugins": list all the plugins at $JANA_PLUGIN_PATH and $EICrecon_MY/plugins *without running* 

### Add podio configurations to "eicrecon -c"
PR #134 
See the description in https://github.com/eic/EICrecon/issues/110#issuecomment-1245410042
 > 1. Move the calls to SetDefaultParameter that are near the top of JEventSourcePodioSimple::Open to be instead in the constructor. This will cause them to be defined without having to try and open a source.
 > 2. Move the calls to SetDefaultParameter that are in EICRootWriterSimple::Init() to its constructor.
> 3. Modify eicrecon to load all of its default plugins when the -c option is given so that parameters defined in the plugins will be listed.

- [x] 1
- [x] 2
- [x] 3

## Others
Items not considered now:
* https://github.com/eic/EICrecon/issues/61#issuecomment-1239329595?
   > To scan all available plugins add "-Pprint_factories=scan_all"
* "eicrecon -b" check. It was designed for the jana benchmark mode, but I am not sure how it would go with eicrecon, especially  the recently added ones by me.
* The cli option to exclude the default plugins since there is already a param "plugins_to_ignore" working. (refer to #90)
   >  - do not attach default plugins
   > - exclude these from the list of default plugins to attach

**Comment by faustus123** [comment]
No, that line should be removed.

**Comment by DraTeots** [comment]
Sorry to pester with this, but it is easy to decide and change in the beginning then when there are already a bunch of scripts using flags: 

https://github.com/eic/EICrecon/discussions/68#discussioncomment-3655114

**Comment by cissieAB** [comment]
Hi, thank you for bring this up. 

I do not quite follow what's going on and what's needed when I read the original post due to my poor EIC background. I guess you are asking me to keep some consistency in the "eicrecon -h" menu. @DraTeots 

Now it looks like this:
```bash
nightly> xmei@localhost:~/eic/dev/EICrecon$ eicrecon
...
Options:
   -h   --help                  Display this message
   -v   --version               Display version information
   -c   --configs               Display configuration parameters
   -l   --loadconfigs <file>    Load configuration parameters from file
   -d   --dumpconfigs <file>    Dump configuration parameters to file
   -b   --benchmark             Run in benchmark mode
   -L   --list_factories        List all the factories without running
   -Pkey=value                  Specify a configuration parameter
   -Pplugin:param=value         Specify a parameter value for a plugin

   --list_default_plugins       List all the default plugins
   --list_available_plugins     List plugins at $JANA_PLUGIN_PATH and $EICrecon_MY


Example:
    eicrecon -Pplugins=plugin1,plugin2,plugin3 -Pnthreads=8 infile.root
    eicrecon -Ppodio:print_type_table=1 infile.root
```

Up to now, I added three options.
- "-L"/"--list_factories"
- "--list_default_plugins"
- "--list_available_plugins"

Are you suggesting me to make the above three options CamelCase? That's a bit weird, since for almost all the 
software, the options read like "--alice-brown-cissie", not quite alike now (--alice_brown_cissie) though...
