### ISSUE TITLE
Implement all algorithms from the Roman Pots mermaid plot

### ISSUE THREAD

**Issue by faustus123** [eic/EICrecon#118]
See the "Roman pods" (typo) diagram in [EICrecon issue #11](https://github.com/eic/EICrecon/issues/11).

**Comment by DraTeots** [comment]
> See the "Roman pods" (typo) diagram in [EICrecon issue #11](https://github.com/eic/EICrecon/issues/11).

I believe it to be copy paste from tracking

**Comment by faustus123** [comment]
This was implemented in PR #168
