### ISSUE TITLE
Reconstruction for the LYSO + SiPM-on-tile ZDC.  

### ISSUE THREAD

**Issue by sebouh137** [eic/EICrecon#1220]
**Is your feature request related to a problem? Please describe.**
Yes.  Current version of the ZDC recon doesn't include reconstruction algorithms we've developed for the SiPM-on-tile ZDC.  Also, the dynamic range for the ZDC ECal (which now uses LYSO crystals) is not sufficient.  

**Describe the solution you'd like**
Add new algorithms, such as HEXPLIT and LogWeightReco to reconstruct clusters of hits from the SiPM-on-tile ZDC.  Add factories as appropriate, and modify the ZDC plugin to include these algorithms, and add the banks to the JEventProcessorPODIO.cc.  Also increase dynamic range for ZDC ECAL.   

**Describe alternatives you've considered**
no alternatives have been considered

**Additional context**

**Comment by sebouh137** [comment]
> Hi @sebouh137! Just checking in on this issue: it looks like PR #1221 resolved this. Is there anything else to address here?

Hi @ruse-traveler , I believe you are correct and that this issue was resolved by PR 1221.  Thanks!

**Comment by ruse-traveler** [comment]
Awesome! Thanks for confirming!
