### ISSUE TITLE
linux-eic-shell.yml: No input available for capybara for push trigger

### ISSUE THREAD

**Issue by veprbl** [eic/EICrecon#1264]
"Error: No artifacts found matching pattern '*.capy'" on `main` CI

https://github.com/eic/EICrecon/actions/runs/7700786196/job/20985889454#step:8:20

https://github.com/eic/EICrecon/blob/cb81e0a4c5185de21bd20bf9132bffee1e9dc5e8/.github/workflows/linux-eic-shell.yml#L846-L851

Looks like [action-download-artifact](https://github.com/dawidd6/action-download-artifact) doesn't work there.

https://github.com/eic/EICrecon/blob/cb81e0a4c5185de21bd20bf9132bffee1e9dc5e8/.github/workflows/linux-eic-shell.yml#L583C59-L583C74

Perhaps, this needs to use a commit of `github.ref_name + "~"`?

**Comment by wdconinc** [comment]
https://github.com/eic/EICrecon/actions/runs/7838582681 @rahmans1
