### ISSUE TITLE
Excessive cluster splitting at high pseudorapidity in EcalBarrelScFi

### ISSUE THREAD

**Issue by veprbl** [eic/EICrecon#1289]
![EcalBarrelScFi](https://github.com/eic/EICrecon/assets/245573/e5f59432-95ee-44dc-ad09-a47149a5e426)

Reproducer using single 1GeV electrons from the 23.12 campaign https://gist.github.com/veprbl/527906251dc8f86c45c99ca502bf5528

cc @Chao1009

**Comment by veprbl** [comment]
@AkshayaVijay Could you, please, look into this? I think, this is quite important to get resolved.

cc @mariakzurek

**Comment by AkshayaVijay** [comment]
> @AkshayaVijay Could you, please, look into this? I think, this is quite important to get resolved.
> 
> cc @mariakzurek

Sure.

**Comment by wdconinc** [comment]
@AkshayaVijay Can you file a pull request with the changes to the clustering parameters that we think are now better than what is there in EICrecon? You can link your slides in that PR for documentation purposes. Even if we don't have the full cluster-to-'relevant'-MCParticle association working yet, it would be helpful to include this in the June campaign.
