### ISSUE TITLE
Add support for ACTS::CylindricalSurfaces in obj output from `draw_surfaces`

### ISSUE THREAD

**Issue by mposik1983** [eic/EICrecon#1330]
**Is your feature request related to a problem? Please describe.**
EICrecon takes DD4HEP surfaces and casts them to ACTS::PlanarSurfaces, however we have DD4HEP geometries which are curved and can not be cast to PlanarSurfaces. Extend EICrecon to use correct ACTS surface based on surface geometry. 

`acts_init] [error] Warning: Attempting cast a Acts::CylinderSurface to Acts::PlaneSurface returns nullptr. This surface will not be added to the .obj output.`

**Describe the solution you'd like**
Allow for curved surfaces to be cast to ACTS::CylindricalSurface

**Describe alternatives you've considered**
none.

**Additional context**

**Comment by wdconinc** [comment]
The error is produced by the following line:
https://github.com/eic/EICrecon/blob/ac3821d47eb4cbd6f39bddaac19710a7840104e0/src/algorithms/tracking/ActsGeometryProvider.cc#L72

That code only(!) creates an obj file with the tracking geometry. The obj format only (easily) supports rectangular surfaces (through simple meshes), so we don't currently export cylinders.

**Comment by wdconinc** [comment]
I've added #1357 which exports full tracking geometry as obj + mtl, and as ply files. You can open those with [meshlab](https://www.meshlab.net) (just open the whole set at once). It approximates the cylinder surfaces through triangulations.
