### ISSUE TITLE
Jet reconstruction takes 60% of the execution time

### ISSUE THREAD

**Issue by veprbl** [eic/EICrecon#1348]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): main
- Which version (or `HEAD` for the most recent on git): HEAD
- Any specific OS or system where the issue occurs? macOS
- Any special versions of ROOT or Geant4?

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. fetch an input file `capybara capy rev 9455e4b097c3218f8f29414f73c89b0e3406dc01 --artifact-name sim_dis_18x275_minQ2=1000_craterlake.edm4hep.root` (replace commit id with HEAD for latest)
2. run `eicrecon -Pplugins=janatop 2024-03-24T00-27-00_9455e4b097c3218f8f29414f73c89b0e3406dc01/sim_dis_18x275_minQ2=1000_craterlake.edm4hep.root`, observe:

```
29.50 s ( 15.7%) edm4eic::ReconstructedParticle:ReconstructedChargedJets
29.62 s ( 15.8%) edm4eic::ReconstructedParticle:ReconstructedJets
30.14 s ( 16.0%) edm4eic::ReconstructedParticle:GeneratedJets
30.20 s ( 16.1%) edm4eic::ProtoCluster:HcalFarForwardZDCIslandProtoClusters
30.61 s ( 16.3%) edm4eic::ReconstructedParticle:GeneratedChargedJets
```

or see on CI #1347

### Expected Result: (what do you expect when you execute the steps above)

Track propagation or EcalBarrelImaging are in the top.

### Actual Result: (what do you get when you execute the steps above)

Jet reconstruction takes most of the time.

**Comment by veprbl** [comment]
This is not an accounting error. For example, I have a reconstruction that takes (according to `command time -v`)
```
Elapsed (wall clock) time (h:mm:ss or m:ss): 10:23.13
```
Then I add `-Ppodio:output_exclude_collections=ReconstructedChargedJets,ReconstructedJets,GeneratedJets,GeneratedJets` and it's now:
```
Elapsed (wall clock) time (h:mm:ss or m:ss): 2:52.64
```

cc @bspage912 @ruse-traveler

**Comment by bspage912** [comment]
We are using FastJet, so I don't know why it would be running slow ...

It looks like you opened this issue on Mar 24, so this has been a persistent feature since at least the factories were reconfigured to use PODIO relations. Do you have timing tests from say the December campaign?

Do you know if all the jet branches take roughly the same time, or are some significantly slower? Also, it looks like you run on a minQ2 = 1000 file, do you have timing info for lower Q2 (should have lower multiplicity)?

**Comment by ruse-traveler** [comment]
Agreed... My 1st guess would be the culprit (or maybe culprits) is one of the full jet collections: I could see fastjet choking on some of the calorimeters with finer segmentation or on a bunch of soft neutrals.

Another thought is that maybe we don't need to have all 4 collections run by default: we know that there are some shortcomings with the existing `MatchClusters` algorithm that (as we've seen) frequently confuse users, so would it be reasonable to only run the charged jets until we have a more thorough energy flow routine?

**Comment by rosijreed** [comment]
What is the default ghost size?  I'd really prefer to be able to keep the full jets even in their current states because my worry is that it will be much harder to have them brought back in the future.  (Maybe good to see as Brian says whether your assumption about the culprit is correct.)

**Comment by bspage912** [comment]
Rosi's comment about the ghost is a good one, area calculations can be real resource hogs. One could run a test with the area determination disabled to see what the change is. I would argue at this stage it is not critical that the calculation be done - as long as we keep the machinery in place for actually doing it. If this is the culprit, we can disable it in the main branch while we try to optimize the settings on the side.

**Comment by ruse-traveler** [comment]
Oh! Good points! TBH I forgot we were running the area calculation since we don't write out the area yet. (Which is another point in favor of disabling it for now...)

I'll run a test to check.
