### ISSUE TITLE
Create Algorithms ServiceSvs

### ISSUE THREAD

**Issue by DraTeots** [eic/EICrecon#136]
Create "Service service service which is not really a service" on EICRecon side. To start integration with independent algorithms.

**Comment by faustus123** [comment]
I'll admit I do worry a little about going so far out of the way to make everything swappable only for us to find 10 years later that we have only ever used one option. I'm not saying we shouldn't do it, but I do have some skepticism.

**Comment by DraTeots** [comment]
Done and works as a prototype. integration with the main code requires further work
