### ISSUE TITLE
jana-generate plugin quibbles

### ISSUE THREAD

**Issue by T-Britton** [eic/EICrecon#147]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): All
- Which version (or `HEAD` for the most recent on git):all
- Any specific OS or system where the issue occurs?no
- Any special versions of ROOT or Geant4?no

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. jana-generate.py Plugin

### Expected Result: (what do you expect when you execute the steps above)
I expect skeleton code, with only lines of code that are needed in (commented out examples are fine.

### Actual Result: (what do you get when you execute the steps above)
I see a defined string "genfit" which ma not be necessary and a TFile/TDirectory which may not e needed.  The Example histogram is actually there.  Init does many things including define the histogram.  In process the filling of this histogram is commented out.  I'd expect either it is commented out everywhere or in everywhere.  You could have an unobservant user who compiles this skeleton and run it.  It might be shocking to to see it produce an empty root file (but wait the histogram is defined)

**Comment by DraTeots** [comment]
Is it JANA2 or EICrecon bug?
