### ISSUE TITLE
B0 Tracking Problem

### ISSUE THREAD

**Issue by zsweger** [eic/EICrecon#1500]
### Environment: (where does this bug occur, have you tried other environments)
- The most recent eicrecon version does not produce reconstructed tracks within the B0 tracker. When running the u-channel rho benchmark over the April simulation campaign, I get [this reconstruction efficiency map](https://eicweb.phy.anl.gov/EIC/benchmarks/physics_benchmarks/-/jobs/3297511/artifacts/file/results/u_rho/benchmark_rho_efficiencies.pdf) for the far-forward region. 
- When using the May simulation campaign, [the new efficiency map](https://eicweb.phy.anl.gov/EIC/benchmarks/physics_benchmarks/-/jobs/3297387/artifacts/file/results/u_rho/benchmark_rho_efficiencies.pdf) is 0 everywhere but the lowest eta values.
- This is true even when not using the simulation campaigns, but using the most recent detector and reconstruction software, as seen in [this test sample](https://eicweb.phy.anl.gov/EIC/benchmarks/physics_benchmarks/-/jobs/3284448/artifacts/file/results/u_rho/benchmark_rho_efficiencies.pdf).

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. Update [`setup.config` in the u-channel rho benchmark](https://github.com/eic/physics_benchmarks/blob/pr/u_channel_sweger/benchmarks/u_rho/setup.config) with `USE_SIMULATION_CAMPAIGN=false`, and `N_EVENTS=500` (the simulation does roughly 20 events per minute, so choose a low number) and commit the changes.
2. After pushing the changes, monitor [GitLab pipelines](https://eicweb.phy.anl.gov/EIC/benchmarks/physics_benchmarks/-/pipelines) for this benchmark. Once completed, check the efficiency map stored in the artifacts under `Artifacts/results/u_rho/benchmark_rho_efficiencies.pdf`

### Expected Result: (what do you expect when you execute the steps above)
- From the April campaign: https://eicweb.phy.anl.gov/EIC/benchmarks/physics_benchmarks/-/jobs/3297511/artifacts/file/results/u_rho/benchmark_rho_efficiencies.pdf

### Actual Result: (what do you get when you execute the steps above)
- From the May campaign: https://eicweb.phy.anl.gov/EIC/benchmarks/physics_benchmarks/-/jobs/3297387/artifacts/file/results/u_rho/benchmark_rho_efficiencies.pdf

**Comment by veprbl** [comment]
cc @ShujieL @minjungkim12 @rahmans1

**Comment by ShujieL** [comment]
Somehow I can not access the files from May. Can you re-attach? @zsweger

**Comment by veprbl** [comment]
Judging by the discussion in https://chat.epic-eic.org/main/pl/5it83iu4gpghxm5kmdn3ntsojw, there is no issue with the tracking. Users who rely on ReconstructedParticle.PID field need to be notified that this field is now filled with detector PID information, but it used to be the MC truth. To access MC truth one has to explicitly depend on MC-Track associations (beware, this potentially makes your analysis less realistic).
