### ISSUE TITLE
`HcalFarForwardZDCImagingProtoClusters` is slow

### ISSUE THREAD

**Issue by veprbl** [eic/EICrecon#1573]
Per 1000 events:
```
39.81 s (  1.1%) edm4eic::CalorimeterHit:HcalFarForwardZDCSubcellHits
3538.76 s ( 98.7%) edm4eic::ProtoCluster:HcalFarForwardZDCImagingProtoClusters
```
https://eicweb.phy.anl.gov/EIC/benchmarks/physics_benchmarks/-/jobs/3651688#L4721

cc @sebouh137

**Comment by wdconinc** [comment]
I guess I was a day late in realizing this. I'll remove `HcalFarForwardZDCImagingProtoClusters` for now.
