### ISSUE TITLE
PODIO event source fails on ~CaloHitContributionCollectionData()

### ISSUE THREAD

**Issue by DraTeots** [eic/EICrecon#159]
### Branch: 

Branch "dmitry-tracking-algo" but yesterday main was also affected. 

The bug appears only when some combination of `-Ppodio:output_include_collections` is set

Run parameters: 

```bash
eicrecon
-Pplugins=tracking_efficiency,tracking_occupancy
-Ppodio:output_include_collections="ReconstructedParticles,TrackParameters,MCParticles,trackerHits,BarrelTrackerHit,EndcapTrackerHit"
-Pnthreads=1
-Ppodio:output_file=/home/romanov/work/data/eicrecon_test/tracking_test_gun.edm4hep.root
-PTracking:CentralTrackerSourceLinker:input_tags=BarrelTrackerHit,BarrelVertexHit,EndcapTrackerHit,MPGDTrackerHit
-Pjana:debug_plugin_loading=1
-Pjana:nevents=200
-Pjana:debug_mode=1
-Pjana:timeout=0
-Ptracking_efficiency:LogLevel=info
-PCKFTracking:CentralTrackerSourceLinker:LogLevel=info
-PCKFTracking:CentralCKFTrajectories:LogLevel=info
-PTracking:CentralTrackingParticles:LogLevel=info
-Pdd4hep:xml_files=/home/romanov/eic/soft/detector/main/compiled/epic/share/epic/epic_tracking_only.xml
-Phistsfile=/home/romanov/work/data/eicrecon_test/ccdis.ana.root
/home/romanov/work/data/eicrecon_test/2022-09-26_ncdis10x100_minq2-1_100ev.edm4hep.root
```

Input file is from tutorials

https://eicaidata.s3.amazonaws.com/2022-09-26_ncdis10x100_minq2-1_100ev.edm4hep.root

Failing at: 

```
__GI_raise 0x00007ffff5eea00b
__GI_abort 0x00007ffff5ec9859
__libc_message 0x00007ffff5f3426e
malloc_printerr 0x00007ffff5f3c2fc
malloc_consolidate 0x00007ffff5f3cad8
_int_free 0x00007ffff5f3dfe0
__gnu_cxx::new_allocator::deallocate new_allocator.h:119
std::allocator_traits::deallocate alloc_traits.h:469
std::_Vector_base::_M_deallocate stl_vector.h:351
std::_Vector_base::~_Vector_base stl_vector.h:332
std::vector::~vector stl_vector.h:680
std::default_delete::operator() unique_ptr.h:81
std::unique_ptr::~unique_ptr unique_ptr.h:292
edm4hep::CaloHitContributionCollectionData::~CaloHitContributionCollectionData CaloHitContributionCollectionData.h:52
edm4hep::CaloHitContributionCollection::~CaloHitContributionCollection CaloHitContributionCollection.cc:17
edm4hep::CaloHitContributionCollection::~CaloHitContributionCollection CaloHitContributionCollection.cc:20
podio::EventStore::clear EventStore.cc:129
JEventSourcePODIOsimple::GetEvent JEventSourcePODIOsimple.cc:219
JEventSource::DoNext(std::shared_ptr<JEvent>) 0x000000000045bd15
JEventSourceArrow::execute(JArrowMetrics&, unsigned long) 0x0000000000462be6
JWorker::loop() 0x000000000046656e
void std::__invoke_impl<void, void (JWorker::*)(), JWorker*>(std::__invoke_memfun_deref, void (JWorker::*&&)(), JWorker*&&) 0x000000000046892a
std::__invoke_result<void (JWorker::*)(), JWorker*>::type std::__invoke<void (JWorker::*)(), JWorker*>(void (JWorker::*&&)(), JWorker*&&) 0x0000000000468858
void std::thread::_Invoker<std::tuple<void (JWorker::*)(), JWorker*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) 0x00000000004687b7
std::thread::_Invoker<std::tuple<void (JWorker::*)(), JWorker*> >::operator()() 0x000000000046876e
std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (JWorker::*)(), JWorker*> > >::_M_run() 0x000000000046874e
<unknown> 0x00007ffff62fede4
start_thread 0x00007ffff60a1609
clone 0x00007ffff5fc6133
```

Easier to read version

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/4732545/192405832-50a0d5ec-bb19-4613-8073-110aa82fd0cb.png">

Full running log
[error.txt](https://github.com/eic/EICrecon/files/9650553/error.txt)

**Comment by faustus123** [comment]
I did run into a crash today trying to write out ReconstructedParticles and EcalEndcapNIslandProtoClusters. The error there was coming in the `prepareforwrite` call in podio (not in `EventStore::clear`).

I did not have time to track it down. When I wrote out everything, it seemed to work which is consistent with the "some combination of -Ppodio:output_include_collections"  statement.

**Comment by faustus123** [comment]
This may now be addressed (not fully fixed) with PR#164.

The issue I saw was due to `edm4eic::ProtoCluster` objects being made with `edm4eic::CalorimeterHit` objects that are labeled internally as "untracked". The "tracked" status of objects looks to be a way for podio to ensure that the object will be written to the output file as part of the EventStore. This is needed since it stores the 1-to-many relations as indexes pointing to the position of the related object in its own collection. If that collection is not also being written to the file, the index lookup will fail (in a nasty way) when the file is read in later. 

The fix in the pending PR is to catch the exception thrown by podio when it encounters an attempt to write an untracked object index. It then removes the offending collection from the list we are writing out. Thus, if the user asks for `ReconsrtructedParticles,EcalEndcapNIslandProtoClusters` to be written, an error message will print saying the `EcalEndcapNIslandProtoClusters` can't be written, but the program will continue and will write out the `ReconstructedParticles`.

This is not a long term solution, but is better than crashing. Please check if this fixes your error as well.

**Comment by DraTeots** [comment]
Yes. After the PR, having the same segfault but now in unique_ptr

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/4732545/192686810-8b84940d-8210-496f-9f65-3efa0d0a7268.png">

```
[INFO] Status: 0 events processed  0.0 Hz (0.0 Hz avg)
malloc_consolidate(): invalid chunk size
Signal: SIGABRT (Aborted)
```

**Comment by DraTeots** [comment]
Yet another bug with podio destruction. Now from Shayam and tracking is failing: 

Thread model: pthreads
140334968206912:
       `- eicrecon (0x55aa4a29a6c1)
        `- /lib/x86_64-linux-gnu/libc.so.6 (0x7fa260ca1af0)
         `- edm4eic::TrackerHit::~TrackerHit() (0x7fa260307e28)
          `- JFactoryT<edm4eic::TrackerHit>::ClearData() (0x7fa25d8fc5ba)
           `- eicrecon (0x55aa4a2bbe52)
            `- eicrecon (0x55aa4a2d016a)
             `- eicrecon (0x55aa4a2d36fc)
              `- /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x7fa2610363d3)
               `- /lib/x86_64-linux-gnu/libc.so.6 (0x7fa260cebb27)
                `- /lib/x86_64-linux-gnu/libc.so.6 (0x7fa260d6e78c)

More info is coming...

**Comment by DraTeots** [comment]
The parameters that got to this issue: 

```bash
#!bin/bash
#source /opt/detector/setup.sh 
source ../epic/install/setup.sh 
source ../EICrecon/install/bin/eicrecon-this.sh
#eicrecon -Pplugins=acts,tracking,BTRK,ECTRK,BVTX,MPGD,tracking_test \ 
 #-PTracking:CentralTrackerSourceLinker:input_tags=BarrelTrackerHit,BarrelVertexHit,EndcapTrackerHit,MPGDTrackerHit \
 #-Ppodio:output_include_collections="ReconstructedParticles,TrackParameters,MCParticles" \
eicrecon -Pplugins=acts,tracking,BTRK,ECTRK,BVTX,MPGD,tracking_occupancy,tracking_efficiency,tracking_test \
 -Pnthreads=1 \
 -Pjana:debug_plugin_loading=1 \
 -Pjana:nevents=3000000 \
 -Pjana:debug_mode=1 \
 -Pjana:timeout=0 \
 -Ptracking_efficiency:LogLevel=info \
 -PTracking:CentralTrackerSourceLinker:LogLevel=info \
 -PCKFTracking:Trajectories:LogLevel=info \
 -Ptracking_efficiency:LogLevel=debug \
 -PTracking:CentralTrackerSourceLinker:LogLevel=trace \
 -PTracking:CentralTrackerSourceLinker:input_tags=BarrelTrackerHit,BarrelVertexHit,EndcapTrackerHit,MPGDTrackerHit \
 -PCKFTracking:Trajectories:LogLevel=trace \
 -PCKFTracking:CentralTrackingParticles:LogLevel=trace \
 -Pacts:MaterialMap=material-maps.cbor \
 -Ppodio:output_file=tracking_test_gun.edm4eic.root \
 -Pdd4hep:xml_files=$DETECTOR_PATH/epic_tracking_only.xml \
 -Ppodio:output_include_collections="ReconstructedParticles,TrackParameters,MCParticles" \
 -Phistsfile=output.ana.root sim.edm4hep.root
```

I'm now checking if I can reproduce.

**Comment by DraTeots** [comment]
Ok, Shayam has a separate issue #169 

Issue of this ticket still persists

**Comment by DraTeots** [comment]
There are now much better crashes in calorimetry part
