### ISSUE TITLE
Calorimeter-Based PID

### ISSUE THREAD

**Issue by ruse-traveler** [eic/EICrecon#1654]
One point discussed during the [July 2024 UGM eID/Reconstruction workfest](https://indico.bnl.gov/event/20727/sessions/7433/#20240725) was the possibility of utilizing calorimeters as an additional prior in determining PID. For example, the calorimeters will be particularly crucial for separating leptons from hadrons (c.f. [EICrecon#1653](https://github.com/eic/EICrecon/issues/1653)).

**Comment by veprbl** [comment]
Closed by https://github.com/eic/EICrecon/pull/1618
