### ISSUE TITLE
Integrate Cluster Shapes into Electron ID

### ISSUE THREAD

**Issue by ruse-traveler** [eic/EICrecon#1655]
As pointed out in [EICrecon#1653](https://github.com/eic/EICrecon/issues/1653), one item discussed during the July 2024 UGM (see the [eID/reco workfest](https://indico.bnl.gov/event/20727/sessions/7433/#20240725)) was the possibility of evolving our existing electron
reconstruction algorithms into a more general lepton/hadron discriminator. Utilizing cluster-shapes in the rejection of non-electrons will be a valuable tool for this.

**Comment by veprbl** [comment]
Closed by https://github.com/eic/EICrecon/pull/1618
