### ISSUE TITLE
Reconstructed x-Bjorken sometimes negative for 10% of the event

### ISSUE THREAD

**Issue by Abiolade1** [eic/EICrecon#1679]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): main
- Which version (or `HEAD` for the most recent on git): 5e39885
- Any specific OS or system where the issue occurs?
- Any special versions of ROOT or Geant4?

### A little description
It is an exclusive DVMP simulation with lAger event generator. The aim is to reconstruct JPsi, scattered electrons, and the scattered proton. I reconstructed the scattered electron using the following algorithms: e' has greater energy, e' has smaller eta, and abs(p_z) of e' has greater value - than the electrons at the J\Psi decay. 

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. Ran the full simulation
2. Ran eicrecon

### Expected Result: (what do you expect when you execute the steps above)
We expect positive values for the reconstructed x-Bjorken, but the result sometimes shows negative. 

### Actual Result: (what do you get when you execute the steps above)
The black plot is the MC and the red plot is the reconstructed events. Other kinematics are consistent. 
<img width="704" alt="Screenshot 2024-11-25 at 11 26 38 AM" src="https://github.com/user-attachments/assets/6d8bae76-2568-47da-bea0-25810ae1166b">

**Comment by Abiolade1** [comment]
I defined x like $ \frac{Q^{2}}{2P \cdot q} $ where $Q^{2} = 2E_{e}E_{e'}(1 - cos(\theta_{e'})$.

I used the reconstructed data set ReconstructedTruthSeededChargedParticles tree. Also tried it for ReconstructedChargedParticles, and got the same result.

**Comment by wdconinc** [comment]
How did you determine which electron to use? How did you handle beam crossing angle?

**Comment by Abiolade1** [comment]
**How did you determine which electron to use?**
I reconstructed the scattered electron using the following algorithms compared to the JPsi electron: 
e' has greater energy, 
e' has smaller eta, and 
abs(p_z) of e' has greater value.

How did you handle beam crossing angle?
Yes, I ran the afterburner. The reconstructed -t distribution looks great, I think the crossing angle only affects the proton beam.

**Comment by wdconinc** [comment]
How does your determination of the x Bjorken compare with the electron method which uses largely similar assumptions and is in the output tree under InclusiveKinematicsElectron?

**Comment by Abiolade1** [comment]
In fact, it has negative values also.

<img width="467" alt="Screenshot 2024-11-25 at 1 14 49 PM" src="https://github.com/user-attachments/assets/cd9b8277-63f3-400c-b66c-2cac47819ed8">

**Comment by bschmookler** [comment]
I think one thing is that at low y, the x and y resolution is very poor
with the scattered electon method. So, it is possible for y to reconstruct
as a negative number, if I remember correctly. Then x can also be negative.

So you should only use the electron method for y>0.1.

**Comment by Abiolade1** [comment]
Great, for this insight.
By y I trust it is the inelasticity not position, right?

**Comment by bschmookler** [comment]
Correct, y is inelasticity variable.

**Comment by veprbl** [comment]
Looks resolved.

**Comment by Abiolade1** [comment]
Yes
