### ISSUE TITLE
Need plugin generator specific to EICrecon

### ISSUE THREAD

**Issue by faustus123** [eic/EICrecon#17]
The jana-generate.py boilerplate code generator generates a CMakeLists.txt that defaults to C++14 if not specified and installs into the JANA plugins directory. This will fail for users wishing to create a private plugin built against a centrally built JANA (e.g. cvmfs). It also will not include EICrecon include directories.

The default CMakeLists.txt needs to add the EICrecon install and source directories to the include path. It also needs to honor user settings for the user's private plugin directory if available. If not specified, then the install should go into the standard EICrecon plugins directory.

Generally, one should be able do the following:

```
eic_mkplugin.py DaveTest
cmake -S DaveTest -B DaveTest/build
cmake --build DavetTest/build --target install -- -j8

eicrecon -pplugins=DaveTest
```
They should then be able to edit the code in DaveTest to use any of the EICrecon reconstruction libraries or services without needing to modify the CMakeLists.txt file.

**Comment by DraTeots** [comment]
I would propose the next template for CMakeLists.txt:

```cmake
cmake_minimum_required(VERSION 3.9)
cmake_policy(SET CMP0074 NEW)  # use the policy to look for <package>_ROOT envar

# Automatically set plugin name the same as the directory name
# Don't forget string(REPLACE " " "_" PLUGIN_NAME ${PLUGIN_NAME}) if this dir has spaces in its name
get_filename_component(PLUGIN_NAME ${CMAKE_CURRENT_LIST_DIR} NAME)
print_header(">>>>   P L U G I N :   ${PLUGIN_NAME}    <<<<")       # Fancy printing

# Function creates ${PLUGIN_NAME}_plugin and ${PLUGIN_NAME}_library targets
# Setting default includes, libraries and installation paths
plugin_add(${PLUGIN_NAME} WITH_STATIC_LIBRARY)

# The macro grabs sources as *.cc *.cpp *.c and headers as *.h *.hh *.hpp
# Then correctly sets sources for ${_name}_plugin and ${_name}_library targets
# Adds headers to the correct installation directory
plugin_glob_all(${PLUGIN_NAME})

# For your convenience:
# Find dependencies
# find_package(EDM4HEP REQUIRED)
# find_package(podio REQUIRED)
# find_package(DD4hep REQUIRED)
# find_package(ROOT REQUIRED)

# Add include directories (works same as target_include_directories)
# plugin_include_directories(${PLUGIN_NAME} SYSTEM PUBLIC ${podio_INCLUDE_DIR} ${EDM4HEP_INCLUDE_DIR} ${DD4hep_INCLUDE_DIRS} ${ROOT_INCLUDE_DIRS})

# Add libraries (works same as target_include_directories)
# plugin_link_libraries(${PLUGIN_NAME})
```

IDK if the seconds commented part is needed, but I thought it is good make a hint that there are plugin_include_directories and plugin_link_libraries

**Comment by faustus123** [comment]
The eicmkplugin.py script was introduced in PR#58 and is now functional.
