### ISSUE TITLE
plugin only version of plugin_add macro

### ISSUE THREAD

**Issue by faustus123** [eic/EICrecon#18]
There will be some plugins for which we will not need/want and associated library. I'm thinking of end-user plugins meant to just make a few histograms. It would be nice to have some option in cmake to build only the plugin and not the library. I'm not sure if this is better as an optional argument to the plugin_add, or by having a different macro (?).

**Comment by DraTeots** [comment]
I thought about it exactly 1 day ago for the very same reason. I have 3 approaches for this: 

## 1 

plugin_... functions like: plugin_add, plugin_include_directories, etc. 

And something like: 

plugin_and_lib_... functions like: plugin_and_lib_add(...), plugin_and_lib_include_directories, etc. 

The later is super verbose but is really easy to understand. If we name it like pluginlib_... it will be obscured and not clear why we use plugin_... in one places and what pluginlib_... means in other. 



## 2 

I thought on other approaches like adding a function:

```cmake
plugin_with_lib()
```

So if it is called after plugin_add, a library is created: 

```cmake
plugin_add(myplugin)
plugin_with_lib(myplugin)  # Now a library will be created
```

But plugin_with_lib is obscure and position dependent. Like 

```cmake
plugin_add(myplugin)
plugin_include_directories(myplugin ${INCLUDE_DIRS})
plugin_with_lib(myplugin)  # (!) Error, include directories are not in lib
```

## 3

Probably the best, add a special word to plugin_add(...)

```cmake

plugin_add(myplugin WITH_STATIC_LIB)   # Now there will be a plugin and a library

```

In terms of usage I think it is the best. But it requires some global parameter for a plugin and it needs to be tested. 

So lets decide what approach would be the best and I'll implement it.

```

**Comment by DraTeots** [comment]
After some experimenting, I would propose

```
plugin_add(myplugin)   # only plugin is built

plugin_add(myplugin WITH_STATIC_LIB)   # builds plugin and static library
```

**Comment by DraTeots** [comment]
https://github.com/eic/EICrecon#plugins-cmake-api

https://github.com/eic/EICrecon#plugin_add
