### ISSUE TITLE
Check the consistency of environment variables between epic setup and eicrecon default

### ISSUE THREAD

**Issue by rahmans1** [eic/EICrecon#184]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): main
- Which version (or `HEAD` for the most recent on git): HEAD
- Any specific OS or system where the issue occurs? N/A
- Any special versions of ROOT or Geant4? N/A

### Steps to reproduce: (give a step by step account of how to trigger the bug)
```
eicrecon -Ppodio:output_include_collections=ReconstructedParticles <ddsim output>
```
### Expected Result: (what do you expect when you execute the steps above)
May be the default path picked up should be DETECTOR_CONFIG instead of DETECTOR in https://github.com/eic/EICrecon/blob/cd75a87b9847bca80fb3d9a84e0e65829a4b1466/src/services/geometry/dd4hep/JDD4hep_service.cc#L58 unless there is a reason it is setup this way. 

### Actual Result: (what do you get when you execute the steps above)
eicrecon by default picks up $DETECTOR_PATH/$DETECTOR.xml. But we do simulation versioning with $DETECTOR_CONFIG [variable](https://github.com/eic/epic/blob/bc74c31d38180240ad1bca556ca208e9558b055c/templates/setup.sh.in)

**Comment by wdconinc** [comment]
I'm going to let @DraTeots handle this.
