### ISSUE TITLE
When no JANA_HOME, EICrecon looks in wrong directories for plugins

### ISSUE THREAD

**Issue by wdconinc** [eic/EICrecon#194]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): v0.1.0
- Which version (or `HEAD` for the most recent on git): v0.1.0
- Any specific OS or system where the issue occurs? linux, eic-shell
- Any special versions of ROOT or Geant4? No

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. `eic-shell`
2. `eicrecon -Ppodio`

### Expected Result: (what do you expect when you execute the steps above)
No error, or at least not the one that I got.

### Actual Result: (what do you get when you execute the steps above)
```console
Invalid JANA parameter '-Ppodio': Expected format -Pkey=value

[ERROR] JPluginLoader: Couldn't load plugin 'podio.so'
  Make sure that JANA_HOME and/or JANA_PLUGIN_PATH environment variables are set correctly.
  Paths checked:
    ./podio.so  =>  File not found
    /usr/local/plugins/podio.so  =>  File not found
    /usr/local/plugins/JANA/podio.so  =>  File not found

[FATAL] Exception: Couldn't find plugin 'podio.so'
```

### Analysis
EICrecon installs plugins to `/usr/local/lib/EICrecon/plugins`, but that is not where it looks to find the plugins. May be a mismatch in installation targets and what is hardcoded in JANA or EICrecon (?).

**Comment by torrijeske** [comment]
I can reproduce the error you see if I do not source eicrecon-this.sh (inside EICrecon/bin/) or set the EICrecon_MY environment variable..

**Comment by DraTeots** [comment]
Now it correctly set to /usr/local/lib/EICrecon/plugins
