### ISSUE TITLE
InclusiveKinematics* collections are not created

### ISSUE THREAD

**Issue by wdconinc** [eic/EICrecon#196]
**Is your feature request related to a problem? Please describe.**
Inclusive kinematics collections are not calculated, not even for truth, making the intended benchmarking of x and Q2 resolution with EICrecon difficult and a job for end-user code that needs to be developed. Multiple common methods of InclusiveKinematics reconstruction were available in the past. As a DIS factory, inclusive kinematics are a widely used quantity.

**Describe the solution you'd like**
InclusiveKinematics algorithms should be ported and their collections filled.

**Describe alternatives you've considered**
End users can calculate x and Q2 in their own code. This is error-prone, non-standard, and can easily overlook effects from beam divergence and energy distributions.

**Comment by DraTeots** [comment]
@vanekjan Could you remind the status of the issue?

**Comment by wdconinc** [comment]
Resolved by #427.
