### ISSUE TITLE
Request to add Chi2 to the Track Parameters Branch

### ISSUE THREAD

**Issue by Simple-Shyam** [eic/EICrecon#200]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like to access chi2 for each track in the TrackParameters Branch. I want Chi2 for further studies.

**Describe alternatives you've considered**

**Additional context**

**Comment by DraTeots** [comment]
Related issue at EDM4eic

https://github.com/eic/EDM4eic/issues/14

**Comment by wdconinc** [comment]
EDM4eic is unrelated and closed as not planned. The functionality requested there is already available in EDM4hep.
