### ISSUE TITLE
TOF PID reconstruction

### ISSUE THREAD

**Issue by DraTeots** [eic/EICrecon#201]
Ensure that all required data is provided. 

Time is available for hits. Length, as discussed, there are 2 cases: 

1. TOF hit is a part of the tracking reconstructed track. Then we need a length of trajectory from the vertex to the TOF hit. 
2. If there is no TOF hit:
    1. project track to the TOF, 
    2. find nearest hits
    3. apply cuts, if OK
    4. get length of the projection

Desirable deadline is October 17th campaign. For now the plan is to have 1 asap and go into 2. 

Related to #173

**Comment by yezhenyu2003** [comment]
PR #263 merged into main
