### ISSUE TITLE
Update HCal insert digitization parameters

### ISSUE THREAD

**Issue by rymilton** [eic/EICrecon#202]
**Is your feature request related to a problem? Please describe.**
The digitization parameters in [HcalEndcapPInsertRawHits.h](https://github.com/eic/EICrecon/blob/main/src/detectors/HCAL/RawCalorimeterHit_factory_HcalEndcapPInsertRawHits.h) and [HcalEndcapPInsertRecHits.h](https://github.com/eic/EICrecon/blob/main/src/detectors/HCAL/CalorimeterHit_factory_HcalEndcapPInsertRecHits.h) aren't as desired. Correct parameters are listed [here](https://github.com/eic/epic/blob/main/calibrations/calo_digi_default.json).

**Describe the solution you'd like**
Update the digitization parameters with the parameters from [here](https://github.com/eic/epic/blob/main/calibrations/calo_digi_default.json).

**Describe alternatives you've considered**
None

**Comment by T-Britton** [comment]
This was addressed by PR #203
