### ISSUE TITLE
Incorrect smearing and parameters for homogeneous Ecal smearing

### ISSUE THREAD

**Issue by bschmookler** [eic/EICrecon#205]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): Main
- Which version (or `HEAD` for the most recent on git): HEAD
- Any specific OS or system where the issue occurs? N/A
- Any special versions of ROOT or Geant4? N/A

There is a difference between what is currently done for the [homogeneous ECal smearing](https://github.com/eic/EICrecon/blob/main/src/algorithms/calorimetry/CalorimeterHitDigi.cc#L148
), and what we very recently put into Juggler [here](https://eicweb.phy.anl.gov/EIC/juggler/-/blob/main/JugDigi/src/components/CalorimeterHitDigi.cpp#L187).

There was a typo in the previous Juggler implementation, which was fixed. It is now consistent with what is shown, for example, in slide 7 [here](https://indico.bnl.gov/event/16284/contributions/65996/attachments/42222/70712/main.pdf).

In addition, on that same slide, the first parameter has units of E^(1/2); so for dd4hep/juggler, which use GeV as energy units, it should be 0.1/sqrt(1000) = 0.00316. This is what we recently put [here](https://eicweb.phy.anl.gov/EIC/benchmarks/physics_benchmarks/-/blob/master/options/reconstruction.py#L495).

These need to be made consistent in EICrecon in this [file](https://github.com/eic/EICrecon/blob/main/src/detectors/EEMC/CalorimeterHit_factory_EcalEndcapPRecHits.h).

**Comment by rymilton** [comment]
Can this get addressed by somebody please? Issue #204 is going to be addressed by copying the corrected ecal files.

**Comment by jizhongling** [comment]
I verified that this issue has been fixed.

**Comment by rymilton** [comment]
Resolved with [PR #236] (https://github.com/eic/EICrecon/pull/236).
