### ISSUE TITLE
Add digitization/recon for the PbWO4 B0 ECal

### ISSUE THREAD

**Issue by ajentsch** [eic/EICrecon#213]
**Is your feature request related to a problem? Please describe.**
Need digitized hit information from B0 ECal - which is just an array of PbWO4 crystals. 

**Describe the solution you'd like**
Hopefully leverage the same recon code from the backward endcap for the B0 ECal.

**Describe alternatives you've considered**
None.

**Additional context**
We have an option for an EMCAL or a preshower/shower max in the B0 magnet. This is to finish out the setup for the Ecal option, which will be the default for now.

**Comment by DraTeots** [comment]
Hello Alex, 

What is the input array name from DD4Hep? Let me check it exists or not

**Comment by ajentsch** [comment]
Hey guys, what is the status on this?

**Comment by DraTeots** [comment]
Is that a forgotten issue?

**Comment by faustus123** [comment]
This was added in PR#271 a couple of weeks ago. It is has not been fully verified by detector experts, but is at the stage we can close this.
