### ISSUE TITLE
Podio 0.16 is out with frame support. EICrecon does not compile with it.

### ISSUE THREAD

**Issue by wdconinc** [eic/EICrecon#239]
**Is your feature request related to a problem? Please describe.**
We are likely to want to shift to podio-0.16 (though not in the immediate term). We will need to fix the compilation issues due to https://github.com/eic/EICrecon/blob/v0.2.3/src/services/io/podio/EICRootReader.h#L63, where `podio::CollectionIDTable*` becomes `std::shared_ptr<podio::CollectionIDTable>` (as part of https://github.com/AIDASoft/podio/pull/323). You can do this backwards incompatible or backwards compatible (or forwards compatible, if you want to fix it while staying on podio-0.15). PodioDataSvc changes to keep eicweb benchmarks working: https://eicweb.phy.anl.gov/EIC/juggler/-/merge_requests/493/diffs

**Comment by DraTeots** [comment]
What is going to be in eic-shell and when?

**Comment by nathanwbrei** [comment]
I'll see what we gain/lose from upgrading and get back to you. If we were to upgrade, when would you want to do it?

**Comment by wdconinc** [comment]
It's all up to you. It's (at this point) just a matter of pushing a button on the container infrastructure side.

**Comment by veprbl** [comment]
This was fixed in #467
