### ISSUE TITLE
Different default_reco_flags.py files for imaging and for sciglass settings

### ISSUE THREAD

**Issue by wdconinc** [eic/EICrecon#247]
**Is your feature request related to a problem? Please describe.**
There is only a single default_reco_flags.py file which has only sciglass. We would like to have another set of settings for imaging, from digitization through clustering. This should not duplicate the parameters for other detectors.

**Comment by DraTeots** [comment]
Imaging and sciglass calorimeters have different factories so different options. So, their parameters are set separately and it doesn't interfere with other parameters. Does it mean that this issue should be closed? @wdconinc ?

**Comment by wdconinc** [comment]
Sure, this can be closed. This reco_flags.py approach will disappear anyway.
