### ISSUE TITLE
EICrecon quits with unresolved symbol TDatabasePDG::TDatabasePDG()

### ISSUE THREAD

**Issue by johnlajoie** [eic/EICrecon#256]
### Environment: (where does this bug occur, have you tried other environments)
Using the latest EICrecon (main) and running on a newly produced ddsim file, eicrecon quits with an undefined symbol: 

`[2022-10-20 19:24:49.094] [acts_init] [info] ActsGeometryProvider initialization complete
eicrecon: symbol lookup error: /gpfs/mnt/gpfs02/sphenix/user/lajoie/EPIC/eic/EICrecon/lib/EICrecon/plugins/algorithms_tracking.so: undefined symbol: _ZN12TDatabasePDGC1Ev
`

Translating this yields: 

`nightly> lajoie@rcas2069:/gpfs/mnt/gpfs02/sphenix/user/lajoie/EPIC/eic$ c++filt _ZN12TDatabasePDGC1Ev
TDatabasePDG::TDatabasePDG()
`
I have verified that this error does not occur when I use eicrecon on the example file from the tutorial. 

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. Run your own ddsim, what I used was: 

`ddsim --steeringFile test.py --compactFile $DETECTOR_PATH/epic_hcal_gdml.xml -G -N 200 --outputFile test.edm4hep.root`

The contents of test.py: 

`from DDSim.DD4hepSimulation import DD4hepSimulation
from g4units import mm, GeV, MeV, degree
SIM = DD4hepSimulation()

SIM.gun.thetaMin = 40*degree
SIM.gun.thetaMax = 140*degree
SIM.gun.distribution = "uniform"
SIM.gun.momentumMin = 10*GeV
SIM.gun.momentumMax = 10*GeV
SIM.gun.particle = "pi+"
SIM.gun.multiplicity = 1
`

2. Run eicrecon - here's the command line I used: 

`eicrecon -Ppodio:output_include_collections-=ReconstructedParticles test.edm4hep.root`

### Expected Result: (what do you expect when you execute the steps above)

eicrecon completes the events in the file....

### Actual Result: (what do you get when you execute the steps above)

See above, program exits with unresolved symbol

**Comment by faustus123** [comment]
This has now been fixed by adding the ROOT::EG library back into the linking. A PR was submitted, reviewed, and merged. A new release v0.2.5 was also tagged with the fix include.

**Comment by johnlajoie** [comment]
Fixed! Thanks David!
