### ISSUE TITLE
CI test failing and unable to reproduce manually.

### ISSUE THREAD

**Issue by faustus123** [eic/EICrecon#273]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch : any
- Which version most recent on git:
- Any specific OS or system where the issue occurs? No
- Any special versions of ROOT or Geant4? No

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. Submit PR and wait for CI to run.

### Expected Result: (what do you expect when you execute the steps above)

Expect all CI tests to pass. Including the running of eicrecon over a few sample events
which is the one part that is failing.

### Actual Result: (what do you get when you execute the steps above)

Output from CI test is below which shows python stack trace when running `run_eicrecon_reco_flags.py`.
The error references lines 852, 827, and 813. This error should have been fixed in commit
[760af23](https://github.com/eic/EICrecon/pull/271/commits/760af2306422f8acd1688aeb740d7ac22133e2db) which came in through PR #271 . When I checkout and build the branch manually that the CI test fails on,
it runs fine. This is done using the latest `eic-shell`. Also, those lines are not the same line numbers
in `run_eicrecon_reco_flags.py` anymore (they were before the fix went in). This makes me wonder if 
an older file somehow is getting used (though I'm having a hard time imagining just how.)

~~~
Run eic/run-cvmfs-osg-eic-shell@main
Run /home/runner/work/_actions/eic/run-cvmfs-osg-eic-shell/main/setup-eic-shell.sh
Checking if there is a working CVMFS mount
CVMFS mount present
Full EIC shell path is /cvmfs/singularity.opensciencegrid.org/eicweb/jug_xl:nightly
Install Singularity
Starting Singularity image from /cvmfs/singularity.opensciencegrid.org/eicweb/jug_xl:nightly
INFO:    instance started successfully
####################################################################
###################### Executing user payload ######################
VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
Traceback (most recent call last):
  File "/usr/local/bin/run_eicrecon_reco_flags.py", line 852, in <module>
    flags_arguments = make_flags_from_records()
  File "/usr/local/bin/run_eicrecon_reco_flags.py", line 827, in make_flags_from_records
    value = value_eval(record[[1](https://github.com/eic/EICrecon/actions/runs/3304351879/jobs/5458949887#step:5:1)])
  File "/usr/local/bin/run_eicrecon_reco_flags.py", line 813, in value_eval
    return str(eval(value))
  File "<string>", line 1, in <module>
NameError: name 'mrad' is not defined
./action_payload.sh: Error on line 12: run_eicrecon_reco_flags.py sim_e_1GeV_20GeV_arches.edm4hep.root rec_e_1GeV_20GeV_arches
/home/runner/work/_actions/eic/run-cvmfs-osg-eic-shell/main/setup-eic-shell.sh: Error on line [28](https://github.com/eic/EICrecon/actions/runs/3304351879/jobs/5458949887#step:5:30): $THIS/run-linux.sh
Error: Process completed with exit code 1.
~~~

**Comment by wdconinc** [comment]
Right, that's a bug in the workflow and it runs the centrally installed version, not the local checkout. Originally it tried to run EICrecon-this.sh (which doesn't work in eic-shell), but now it just sets JANA_HOME. 

I'll get it fixed.
