### ISSUE TITLE
cmake gives confusing info due to CMP 0074 (?)

### ISSUE THREAD

**Issue by wdconinc** [eic/EICrecon#28]
When not setting JANA_ROOT, the response from cmake is:
```
-- EICRecon: Set default PLUGIN_OUTPUT_DIRECTORY
-- EICRecon: PLUGIN_OUTPUT_DIRECTORY: plugins
-- EICRecon: Set default PLUGIN_OUTPUT_DIRECTORY
-- EICRecon: PLUGIN_LIBRARY_OUTPUT_DIRECTORY: lib
-- 
===============================================
    B U I L D   E I C R E C O N   P A R T S    
===============================================
-- 
>>>>   L I B R A R Y :   algorithms    <<<<
-------------------------------------------
CMake Error at algorithms/CMakeLists.txt:9 (find_package):
  By not providing "FindJANA.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "JANA", but
  CMake did not find one.

  Could not find a package configuration file provided by "JANA" with any of
  the following names:

    JANAConfig.cmake
    jana-config.cmake

  Add the installation prefix of "JANA" to CMAKE_PREFIX_PATH or set
  "JANA_DIR" to a directory containing one of the above files.  If "JANA"
  provides a separate development package or SDK, be sure it has been
  installed.
```
This indicates that JANA_DIR should be set, but that doesn't actually work.

Steps to reproduce:
1. `docker run --rm -it -v /cvmfs:/cvmfs:shared ghcr.io/aidasoft/ubuntu2004:latest /bin/bash`
2. `source /cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-ubuntu2004-gcc9-opt/setup.sh`
3. `git clone https://github.com/JeffersonLab/JANA2 /tmp/JANA2`
4. `git clone https://github.com/eic/EICrecon /tmp/EICrecon`
5. `cmake -B /tmp/JANA2/build -S /tmp/JANA2 -DCMAKE_INSTALL_PREFIX=/tmp/JANA2 -DCMAKE_CXX_STANDARD=17 -DUSE_PYTHON=ON -DUSE_ROOT=ON -DUSE_XERCES=ON -DXercesC_DIR=/cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-ubuntu2004-gcc9-opt -DUSE_ZEROMQ=ON`
6. `make -C /tmp/JANA2/build -j install`
7a. `cmake -B /tmp/EICrecon/build -S /tmp/EICrecon/src -DCMAKE_INSTALL_PREFIX=/tmp/EICrecon -DJANA_DIR=/tmp/JANA2`
7b. `cmake -B /tmp/EICrecon/build -S /tmp/EICrecon/src -DCMAKE_INSTALL_PREFIX=/tmp/EICrecon -DJANA_ROOT=/tmp/JANA2`

Step 7a fails even though it says (as above) to use JANA_DIR. Step 7b succeeds.

**Comment by faustus123** [comment]
This seems similar to the issue in the thread on the dd4hep geometry. There, Dmitry says one needs to source the `setup.sh` file to setup the environment so dd4hep knows where to find the geometry etc. Here, one should source the `/tmp/JANA2/bin/jana-this.(c)sh` script generated by the build so EICrecon will know where to look for it. Otherwise, one must specify it explicitly to cmake as you have done in 7b.

**Comment by faustus123** [comment]
You are correct though the cmake error is misleading. Maybe your suggestion was to detect this ourselves and print a more useful error?

**Comment by wdconinc** [comment]
My suggestion is to figure out what makes CMake print a message that is incorrect. If it is due to our choice of forcing new CMP-0074 behavior with a pre-3.12 default policy set (3.9), then we may want to consider if it doesn't make sense instead to go to minimum 3.12 and do the standard thing.

See e.g. https://indico.jlab.org/event/420/contributions/7961/attachments/6507/8734/CMakeSandCroundtable.slides.pdf for some further discussion, including that "modern cmake" is what started with 3.12 (including, incidentally, more consistent policy setting, see slide ).

I don't think this has anything to do with sourcing jana-this.sh or so.

**Comment by sly2j** [comment]
My preference would be to just move the minimum version to 3.12 and put pressure on legacy systems to update (they will mostly use containerized setup anyway). Don't think we should be developing at this point with one arm tied behind our back. Maybe something to discuss on one of our next meetings.

**Comment by faustus123** [comment]
I don't have an issue going to 3.12 as the minimum.

**Comment by DraTeots** [comment]
There were many changes at that time for CMake (look at release history of 3.13, 3.14 etc.) Especially there was changing behavior of relative paths:

- in CMAKE 3.12 target_sources relative paths are from starts_with.cmake that declared a target
- in CMAKE 3.13 target_sources relative paths are from starts_with.cmake calling target_sources


CERN ROOT CMake requirement: 

```cmake
if(APPLE)
  cmake_minimum_required(VERSION 3.19 FATAL_ERROR)
else()
  cmake_minimum_required(VERSION 3.16 FATAL_ERROR)
endif()
```

ACTS requires 3.14,  DD4Hep 3.12, Geant4 11.1 requires 3.16

I would go with 3.16 minimum

**Comment by wdconinc** [comment]
Fyi, you may want to look into why ROOT on Mac is requiring 3.19, https://github.com/root-project/root/blob/master/CMakeLists.txt#L8. It is requiring 3.16 elsewhere.
