### ISSUE TITLE
EDM4HEP is found but cmake still wants me to set EDM4HEP_ROOT

### ISSUE THREAD

**Issue by wdconinc** [eic/EICrecon#29]
Despite finding EDM4HEP in many `find_package(EDM4HEP REQUIRED)` lines, cmake still insists on setting environment variables:
```
Generating datamodel_glue.h ...
ERROR: EDM4HEP_ROOT env. variable is None or empty and no EDM4HEP=/path/to/edm4hep on command line!
       Please point EDM4HEP_ROOT to edm4hep installation root.
       This script looks for '{EDM4HEP_ROOT}/include/edm4hep/*Collection.h'
```
Generating `datamodel_glue.h` should be possible with the responses from `FindEDM4HEP.cmake` without setting environment variables.

**Comment by faustus123** [comment]
Yes, you're right. I started implementing this, but never finished it. I made the change and put it in [PR#32](https://github.com/eic/EICrecon/pull/32)
