### ISSUE TITLE
SurfaceError + missing tracks in output when tracking factories fail once

### ISSUE THREAD

**Issue by nschmidtALICE** [eic/EICrecon#306]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): main
- Which version (or `HEAD` for the most recent on git): HEAD
- Any specific OS or system where the issue occurs? no
- Any special versions of ROOT or Geant4? no

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. simulate any single particle events in epic_arches with ddsim
2. run output through latest eicrecon version
3. You will encounter two warnings while running eicrecon:
```
[2022-11-03 12:01:20.598] [JEventProcessorPODIO] [warning] Exception adding PODIO type 'edm4eic::ReconstructedParticle:ReconstructedChargedParticles': Value called on error value: SurfaceError: Global to local transformation failed: position not on surface. [1].
[2022-11-03 12:01:20.615] [JEventProcessorPODIO] [warning] Exception adding PODIO type 'edm4eic::MCRecoParticleAssociation:ReconstructedChargedParticlesAssociations': Value called on error value: SurfaceError: Global to local transformation failed: position not on surface. [1].
```
4. only reconstructed tracks up to this warning will be included in the output
5. optional: compare MCParticle branch size and ReconstructedChargedParticles branch size (you will see all MC particles but only a handful (1-200 at most) tracks

### Expected Result: (what do you expect when you execute the steps above)
One would expect a track for most particles to be in the output.

### Actual Result: (what do you get when you execute the steps above)
Only a negligible amount of ReconstructedChargedParticles are present.

### Temporary (but possibly bad) fix:
in EICrecon/src/services/io/podio/JeventProcessorPODIO.cc modify the "catch condition" to:
```
catch(std::exception &e) {
            // Limit printing warning to just once per factory
            std::string fac_name = fac->GetObjectName() + ":" + fac->GetTag();
            if (m_is_first_event) {
                failing_factories.insert(fac_name);
                m_log->warn("Exception adding PODIO type '{}:{}': {}.", fac->GetObjectName(), fac->GetTag(), e.what());
            }
        }
```
to only exclude factories that fail on the first event. This, however, does not fix the underlying surface issue! It just allows to at least analyze outputs again.

**Comment by DraTeots** [comment]
Kind of can't reproduce. How exactly you run eicrecon (are you using flags_reco.py or what are the parameters)? 

What files do use as an input?

**Comment by nschmidtALICE** [comment]
This problem has been present in the central simulation campaign as well. You can effectively use the full chain from the campaign to reproduce it.
