### ISSUE TITLE
JeventProcessorPODIO should fall hard on factory exception

### ISSUE THREAD

**Issue by DraTeots** [eic/EICrecon#316]
Currently if a factory fails it is added to failing list and is never called again. This leads to silencing errors and hard time debugging them. 
Let be explicit and let fail what fails. 

I strongly believe that if there is an isolated algorithm/factory/processor that produces something and we want a package to be modular, this algorithm should decide if it can recover and run further on error or not. If and error in form of exception goes outside of an algorithm JANA2/EICrecon should fall. Period. 

Another pitch: Algorithms should work and not fail, PODIO is not the place to hide their failures and errors. 

Since it is a change that breaks behavior, I would propose not to change the default behavior during this campaign but to add a flag that controls it. 

P.S. This situation is especially messy, because PODIO can be the only reason if factory is called or not, depending on running configuration. Imagine if there is a plugin, that consumes SomeData. Then when this plugin will try to get SomeData, underlying factory/algorithm will fail and EICrecon will fall. Now if this plugin is not attached, but SomeData is in output collection - algorithm failure will be silenced and EICrecon will not fall on the same error. Brrr

**Comment by DraTeots** [comment]
Related 

https://github.com/eic/EICrecon/issues/306

**Comment by nathanwbrei** [comment]
Agreed. Would be a simple change.
