### ISSUE TITLE
More licensing issues

### ISSUE THREAD

**Issue by wdconinc** [eic/EICrecon#333]
I was alerted to the fact that more LGPL-licensed code was copied into EICrecon. In this case it concerns files in `src/services/Io/podio`, in particular the files RootWriter and EventStore which are copied from the podio project. Please remove that code or use it in accordance with the license. We really cannot endanger our relationship with podio by using their code in violation of the license.

@faustus123

**Comment by nathanwbrei** [comment]
This was me, not David. David very thoughtfully attempted to rewrite podio's root IO from scratch. The good news is that we are working with the podio people to migrate to podio frames instead. This code is temporary for a wide variety of reasons, many already discussed.

**Comment by DraTeots** [comment]
Hope this one is finished or became not relevant with recent PODIO changes

**Comment by wdconinc** [comment]
Not resolved; code still there. @DraTeots don't close issues because "you think" they are not relevant anymore. Ask first of you don't know.

**Comment by DraTeots** [comment]
I assumed you would reopen it if needed, which you perfectly did.

**Comment by wdconinc** [comment]
This issue is not applicable anymore, as no known licensing issues remain or have appeared in the past year.
