### ISSUE TITLE
Crashes in eic::ROOTWriter

### ISSUE THREAD

**Issue by veprbl** [eic/EICrecon#347]
### Environment: (where does this bug occur, have you tried other environments)
- main
- c6d10db1cfbe4b9a33a298210f42aec87c25812e
- x86_64-linux

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. Simulate 100 events with ddsim with latest epic_arches
2. `run_eicrecon_reco_flags.py sim.edm4hep.root reco.edm4hep.root`

### Expected Result: (what do you expect when you execute the steps above)
No crashes

### Actual Result: (what do you get when you execute the steps above)
```output
Thread model: pthreads
140736806012480:
       `- lib/libc.so.6 (0x7ffff5bd0c00)
        `- eic::ROOTWriter::setBranches(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, podio::CollectionBase*>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, podio::CollectionBase*> > > const&) (0x7ffff2902bc8)
         `- eic::ROOTWriter::writeEvent() (0x7ffff2903e97)
          `- JEventProcessorPODIO::Process(std::shared_ptr<JEvent const> const&) (0x7ffff283c1e3)
           `- JEventProcessor::DoMap(std::shared_ptr<JEvent const> const&) (0x7ffff5272f7c)
            `- bin/eicrecon (0x456b44)
             `- bin/eicrecon (0x460514)
              `- lib/libstdc++.so.6 (0x7ffff5f783d4)
               `- lib/libc.so.6 (0x7ffff5c1be96)
                `- clone (0x7ffff5ca1e54)
```
and later
```
Thread model: pthreads
140737307110336:
       `- lib/libc.so.6 (0x7ffff5bd0c00)
        `- TStreamerInfo::GetActualClass(void const*) const (0x7ffff78c186a)
         `- TTree::BranchImpRef(char const*, TClass*, EDataType, void*, int, int) (0x7ffff6da5333)
          `- eic::ROOTWriter::finish() (0x7ffff2901e88)
           `- JEventProcessor::DoFinalize() (0x7ffff5273315)
            `- bin/eicrecon (0x456011)
             `- bin/eicrecon (0x44d168)
              `- bin/eicrecon (0x448d21)
               `- bin/eicrecon (0x42cb1c)
                `- bin/eicrecon (0x422fd9)
                 `- bin/eicrecon (0x416b72)
                  `- lib/libc.so.6 (0x7ffff5bbc24e)
                   `- __libc_start_main (0x7ffff5bbc309)
                    `- bin/eicrecon (0x418da5)
```
Full log file: https://gist.github.com/4f7727d53f3da53b4b5dd6001ca55f11

**Comment by faustus123** [comment]
In the full log I see a lot of messages like this:

~~~
Error in <TTree::Branch>: The class requested (vector<podio::ObjectID>) for the branch "HcalBarrelClusters#0" is an instance of an stl collection and does not have a compiled CollectionProxy. Please generate the dictionary for this collection (vector<podio::ObjectID>) to avoid to write corrupted data.
~~~

This looks like possibly an issue with the root dictionaries. I don't see these messages when running the latest code nor am I seeing the crashes. 

Could you give more information about the system this is running on and the detailed commands used to generate the simulated events and then run eicrecon?

**Comment by veprbl** [comment]
@faustus123 Your pointer was spot-on. I wasn't attentive, as PODIO on linux requires its libraries to be in `LD_LIBRARY_PATH`. That's also the case when running dd4hep. It works now.

I wonder, do you also see the "failed to attach" messages, as in:
```
[DEBUG] JPluginLoader: Looking for './log.so' ....
[DEBUG] JPluginLoader: Failed to attach './log.so'
[DEBUG] JPluginLoader: Looking for '/lib/EICrecon/plugins//log.so' 
[DEBUG] JPluginLoader: Found!
```

**Comment by aniakowalewska** [comment]
@veprbl it seems that I have the same issue as you above. Could I ask what you exactly did to point the libraries in proper path?

**Comment by aniakowalewska** [comment]
Thread model: pthreads
140404338694656: 
       `- eicrecon (0x5637f9fd1a7a)
        `- /lib/x86_64-linux-gnu/libc.so.6 (0x7fb26edbef90)
         `- podio::ROOTReader::openFiles(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) (0x7fb26d0abff3)
          `- podio::ROOTReader::openFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (0x7fb26d0ac3c9)
           `- JEventSourcePODIOsimple::Open() (0x7fb2686bf46f)
            `- void std::__invoke_impl<void, void (JEventSource::*)(), JEventSource*>(std::__invoke_memfun_deref, void (JEventSource::*&&)(), JEventSource*&&) (0x7fb268663b77)
             `- std::__invoke_result<void (JEventSource::*)(), JEventSource*>::type std::__invoke<void (JEventSource::*)(), JEventSource*>(void (JEventSource::*&&)(), JEventSource*&&) (0x7fb2686598ca)
              `- std::call_once<void (JEventSource::*)(), JEventSource*>(std::once_flag&, void (JEventSource::*&&)(), JEventSource*&&)::{lambda()#1}::operator()() const (0x7fb268651cda)
               `- std::once_flag::_Prepare_execution::_Prepare_execution<std::call_once<void (JEventSource::*)(), JEventSource*>(std::once_flag&, void (JEventSource::*&&)(), JEventSource*&&)::{lambda()#1}>(void (JEventSource::*&)())::{lambda()#1}::operator()() const (0x7fb2686598f9)
                `- std::once_flag::_Prepare_execution::_Prepare_execution<std::call_once<void (JEventSource::*)(), JEventSource*>(std::once_flag&, void (JEventSource::*&&)(), JEventSource*&&)::{lambda()#1}>(void (JEventSource::*&)())::{lambda()#1}::_FUN() (0x7fb26865990a)
                 `- /lib/x86_64-linux-gnu/libc.so.6 (0x7fb26ee10e37)
                  `- /home/ania/eic/EICrecon/lib/EICrecon/plugins/podio.so (0x7fb268648654)
                   `- void std::call_once<void (JEventSource::*)(), JEventSource*>(std::once_flag&, void (JEventSource::*&&)(), JEventSource*&&) (0x7fb268651d2f)
                    `- JEventSource::DoInitialize() (0x7fb268650f7e)
                     `- eicrecon (0x5637fa01aae1)
                      `- eicrecon (0x5637fa00885a)
                       `- eicrecon (0x5637f9feb794)
                        `- eicrecon (0x5637f9feb93f)
                         `- eicrecon (0x5637f9fd4ea6)
                          `- eicrecon (0x5637f9fce50f)
                           `- /lib/x86_64-linux-gnu/libc.so.6 (0x7fb26edaa18a)
                            `- __libc_start_main (0x7fb26edaa245)
                             `- eicrecon (0x5637f9fce391)

**Comment by aniakowalewska** [comment]
@veprbl I see that during ddsim step I have only EVENT;1	Geant4 EVENT information . And should have 
  KEY: TTree	events;3	Events tree [current cycle]
  KEY: TTree	events;2	Events tree [backup cycle]
  KEY: TTree	metadata;1	Metadata tree
  KEY: TTree	run_metadata;1	Run metadata tree
  KEY: TTree	evt_metadata;1	Event metadata tree
  KEY: TTree	col_metadata;1	Collection metadata tree

So, I will post it to the helpdesk on Matermost. Thank you.

**Comment by veprbl** [comment]
Your crash seems to be different. Must be the input file, indeed.

**Comment by aniakowalewska** [comment]
Dear @veprbl thank you, yes I solved the problem. It was mistake from my side: I changed the name of .edm4hep.root to _edm4hep_smth_.root  file. Apologise for bother you then.
