### ISSUE TITLE
Regression: cmake fails since no datamodel_includes.h after #32

### ISSUE THREAD

**Issue by wdconinc** [eic/EICrecon#35]
Should have tested more, I guess... This now fails with the following:
```console
>>>>   P L U G I N :   podio    <<<<
------------------------------------
CMake Error at /opt/local/cmake/RootMacros.cmake:442 (message):
  Cannot find header datamodel_includes.h to generate dictionary
  G__datamodel_vectors for.  Did you forget to set the INCLUDE_DIRECTORIES
  property for the current directory?
Call Stack (most recent call first):
  services/io/podio/CMakeLists.txt:29 (root_generate_dictionary)

-- Configuring incomplete, errors occurred!
See also "/home/wdconinc/git/EICrecon/build/CMakeFiles/CMakeOutput.log".
```

https://github.com/eic/EICrecon/blob/5cad2a399ccd5fe98300420191f39ccbd5e36e39/src/services/io/podio/CMakeLists.txt#L29 We probably should remove the include here, which is non-existent at cmake time.

_Originally posted by @wdconinc in https://github.com/eic/EICrecon/issues/32#issuecomment-1207511917_

**Comment by faustus123** [comment]
Ugh. This is my bad. I saw it in there and removed it knowing it was a generated file, forgetting that I had left it in on purpose for this exact reason. I just put it back, submitted a PR and merged it. Sorry about that.
