### ISSUE TITLE
Mismatch with tracker names in reco_flags.py

### ISSUE THREAD

**Issue by rahmans1** [eic/EICrecon#406]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): main
- Which version (or `HEAD` for the most recent on git): HEAD

### Steps to reproduce: (give a step by step account of how to trigger the bug)
reco_flags.py uses <trackername>RawHit and <trackername>Hit whereas the tracker names in detector plugins is set somewhat inconsistently as <trackername>DigiHits and <trackername>RecHits. 
### Expected Result: (what do you expect when you execute the steps above)
The nomenclature should match. Ideally should be <trackername>RawHits and <trackername>RecHits in both places.

**Comment by c-dilks** [comment]
See also https://github.com/eic/EICrecon/issues/391

**Comment by rahmans1** [comment]
> See also #391

Thanks. Seems like there was already a detailed entry on this.
