### ISSUE TITLE
eicrecon-this.sh does not set shared library path properly for custom build

### ISSUE THREAD

**Issue by rahmans1** [eic/EICrecon#407]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): main
- Which version (or `HEAD` for the most recent on git): HEAD

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. Clone, build and install eicrecon under eicshell environment
2. cd install/bin
3. source eicrecon-this.sh
4. Run eicrecon 

### Expected Result: (what do you expect when you execute the steps above)
Expect to pick up shared libraries from install/lib/EICrecon/plugins of the custom location. 

### Actual Result: (what do you get when you execute the steps above)
Automatically picks up the shared libraries from /usr/local unless the variable JANA_PLUGIN_PATH is set explicitly to the custom install location.

**Comment by faustus123** [comment]
I put in what should be a fix for this in PR #425. I will assign you as a reviewer so you can check if it fixes the issue for you before merging it.

**Comment by veprbl** [comment]
I believe, this was resolved in #842
