### ISSUE TITLE
`TDatabasePDG` is not thread safe

### ISSUE THREAD

**Issue by c-dilks** [eic/EICrecon#417]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): `main`
- Which version (or `HEAD` for the most recent on git):
- Any specific OS or system where the issue occurs?
- Any special versions of ROOT or Geant4?

### Steps to reproduce: (give a step by step account of how to trigger the bug)
See https://github.com/root-project/root/issues/11580

We use this in the following:
```
src/algorithms/tracking/TruthTrackSeeding.h
src/algorithms/tracking/TruthTrackSeeding.cc
src/algorithms/tracking/TrackParamTruthInit.h
src/algorithms/tracking/TrackParamTruthInit.cc
src/algorithms/pid/IrtCherenkovParticleID.h    (in dev branch `irt-algo`)
src/algorithms/pid/IrtCherenkovParticleID.cc   (in dev branch `irt-algo`)
```

Thanks to @wdconinc for pointing this out in #416.

### Potential Solutions
- Use a mutex
- Contribute a PR to `root` to fix the issue there for all
- Port Juggler's [particle service](https://eicweb.phy.anl.gov/EIC/juggler/-/blob/main/JugBase/src/components/ParticleSvc.cpp)

**Comment by wdconinc** [comment]
> Port Juggler's particle service

I wouldn't necessarily simply port the service from juggler: it was quick to replicate the particle table, but would have been better to use an external reference for that, in particular if more info will be needed in the future.

I'd probably suggest a service that initializes its table based on TDatabasePDG and then continues to serve it in a thread safe way.

**Comment by DraTeots** [comment]
Agree with @wdconinc
