### ISSUE TITLE
No smearing in truth track seeding

### ISSUE THREAD

**Issue by osbornjd** [eic/EICrecon#432]
The truth track seeder just takes the truth track parameters and uses them as the input "reco" seed parameters. This is not a good idea as the resulting fit from the Kalman Filter can be highly biased by the input seed parameters - in general, the Acts::KalmanFilter (like any KF) is very sensitive to the input track parameters and covariance associated to it. We should implement some, presumably settable, Gaussian smearing parameter into [TruthTrackParamInit](https://github.com/eic/EICrecon/blob/main/src/algorithms/tracking/TrackParamTruthInit.cc) to ensure that the resulting track fits are not as biased.

**Comment by osbornjd** [comment]
Looks like https://github.com/eic/EICrecon/pull/399 is an initial solution to this problem

**Comment by DraTeots** [comment]
@osbornjd can we close it now or could you specify what else needs to be done
