### ISSUE TITLE
MatchClusters factory is not actually calling an algorithm

### ISSUE THREAD

**Issue by wdconinc** [eic/EICrecon#454]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): `main`
- Which version (or `HEAD` for the most recent on git): `HEAD`

### Expected Result: (what do you expect when you execute the steps above)
MatchClusters factory should call the algorithm, as implied.

### Actual Result: (what do you get when you execute the steps above)
No actual matching of clusters to tracks is done.

**Comment by DraTeots** [comment]
Let me copy paste (almost) the explanation of what is going on: 

1. Currently only particles from tracking are being put into ReconstructedParticles and here are the reasons:
 
	• Matching tracking particles and calorimeter clusters was done in Juggler through matching of both to same MCParticle.
	• Cluster matching was relying on objects associations in PODIO data model.
	• The code that propagates those associations from DD4Hep file was originally ported but then deactivated (commented out). Without proper handling of POIO those associations caused memory corruption problems. Also, associations are not saved correctly to the output PODIO and all that was the reason to switch them off.
	• MatchClusters_factory is pretty simple implementation, which just goes through two for loops looking the same MCParticles for tracking and clusters. But without the associations it can’t be done and that is the reason why it is empty. 
	
2. Why does it work for tracking then? – Actually, the tracking matching is not based on associations but on comparing reconstructed momentums with MC particles momentums. It also has its own issues so it would be better to make it rely on associations as they will be working. 

3. What is the priority and timescale for fixing it? – The issues with associations and matching are a #1 priority for the upcoming simulation campaign. The issue fully depends on PODIO rewrite that is being done by @nathanwbrei . As soon as it is closed and Wouter would update podio for the stack I will fix the associations and matching algorithm. We also then will use truthful associations matching for tacking.

**Comment by wdconinc** [comment]
We have cluster matching now.
