### ISSUE TITLE
edm4hep -> eicd

### ISSUE THREAD

**Issue by faustus123** [eic/EICrecon#47]
The data model will not be pure edm4hep but will instead be the eicd model that extends edm4hep. This has now been moved to eic/eicd. This needs to be updated in EICrecon (including the top-level build instructions).

**Comment by DraTeots** [comment]
JIC I can do this on Sunday. Two days on vacation

**Comment by DraTeots** [comment]
JIC edpm install eicd during EICrecon chain installation

https://github.com/eic/EICrecon#edpm-installation

**Comment by faustus123** [comment]
This was done some time ago.
