### ISSUE TITLE
Implement splitting for Island Clustering

### ISSUE THREAD

**Issue by veprbl** [eic/EICrecon#478]
**Is your feature request related to a problem? Please describe.**

This is currently disabled:
https://github.com/eic/EICrecon/blob/9f78e08daead845560da5aa34c9fa6dccfbd5648/src/detectors/BEMC/ProtoCluster_factory_EcalBarrelSciGlassProtoClusters.h#L31
Allegedly it's because it doesn't work.

**Describe the solution you'd like**
Splitting is fixed and enabled for all applicable calorimeters.

**Describe alternatives you've considered**

**Additional context**

**Comment by veprbl** [comment]
From what I see in the code, the splitting was supposed to rely on local maxima. The actual cell allocation is effectively not implemented for two or more maxima:
https://github.com/eic/EICrecon/blob/19cd2768503e893dc396b76575da6fc13a99cb76/src/algorithms/calorimetry/CalorimeterIslandCluster.h#L223-L244

**Comment by wdconinc** [comment]
Exists in https://github.com/eic/juggler/blob/main/JugReco/src/components/CalorimeterIslandCluster.cpp#L435
