### ISSUE TITLE
Symbol not found: vtable for rich::IrtGeoDRICH

### ISSUE THREAD

**Issue by veprbl** [eic/EICrecon#483]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): main
- Which version (or `HEAD` for the most recent on git): v0.6.0
- Any specific OS or system where the issue occurs? macOS
- Any special versions of ROOT or Geant4? no

### Steps to reproduce: (give a step by step account of how to trigger the bug)
Compile on macOS with `LDFLAGS=-Wl,-undefined,dynamic_lookup`, run

### Expected Result: (what do you expect when you execute the steps above)
Plugin can load

### Actual Result: (what do you get when you execute the steps above)

```
    ./log.so  =>  File not found
    /tmp/eicrecon/lib/EICrecon/plugins//log.so  =>  Loaded successfully
    ./dd4hep.so  =>  File not found
    /tmp/eicrecon/lib/EICrecon/plugins//dd4hep.so  =>  Loaded successfully
    ./acts.so  =>  File not found
    /tmp/eicrecon/lib/EICrecon/plugins//acts.so  =>  Loaded successfully
    ./richgeo.so  =>  File not found
    /tmp/eicrecon/lib/EICrecon/plugins//richgeo.so  =>  Loaded successfully
    ./rich.so  =>  File not found
    /tmp/eicrecon/lib/EICrecon/plugins//rich.so  =>  Loading failure: dlopen(/tmp/eicrecon/lib/EICrecon/plugins//rich.so, 137): Symbol not found: __ZTVN4rich11IrtGeoDRICHE
  Referenced from: /tmp/eicrecon/lib/EICrecon/plugins//rich.so
  Expected in: flat namespace
```

**Comment by veprbl** [comment]
The issue here is due to the default linker mode on macOS using the Two-level namespaces. For that, each symbol is identified not only by its mangled name, but also the associated library. The symbol itself is exported from richgeo.so:
```
% nm /tmp/eicrecon/lib/EICrecon/plugins//richgeo.so | grep __ZTVN4rich11IrtGeoDRICHE       (git)-[pr/root_macros_mv]-% 
00000000000175b8 S __ZTVN4rich11IrtGeoDRICHE
```
But the rich.so plugin doesn't know which library name it is, so it looks things up in the flat namespace instead. I haven't figured out how to compile EICrecon entirely with a flat namespace only.

**Comment by veprbl** [comment]
I also how some questions regarding separation of services/geometry/rich/richgeo from services/geometry/rich. What is even expected API surface of a plugin? Shouldn't we strive to keep it to a minimum, if possible?

In this specific case, the rich library is a wrapper for a service [1], and richgeo is a plugin for that service, not for EICrecon. cc @c-dilks regarding that

[1] https://github.com/eic/EICrecon/blob/main/src/services/geometry/rich/RichGeo_service.cc

**Comment by veprbl** [comment]
@c-dilks Our messages crossed. I don't see how this is relevant to IRT. In terms of CMake a working workaround for this case is:
```diff
diff --git a/src/services/geometry/rich/CMakeLists.txt b/src/services/geometry/rich/CMakeLists.txt
index 30ca83d..2cd5729 100644
--- a/src/services/geometry/rich/CMakeLists.txt
+++ b/src/services/geometry/rich/CMakeLists.txt
@@ -22,3 +22,5 @@ plugin_glob_all(${PLUGIN_NAME})
 plugin_add_dd4hep(${PLUGIN_NAME})
 plugin_add_irt(${PLUGIN_NAME})
 plugin_add_acts(${PLUGIN_NAME})
+
+target_link_libraries(${PLUGIN_NAME}_plugin richgeo_plugin)
```
Also, this should not affect linux with its ld dynamic linker.

**Comment by c-dilks** [comment]
> I also how some questions regarding separation of services/geometry/rich/richgeo from services/geometry/rich. What is even expected API surface of a plugin? Shouldn't we strive to keep it to a minimum, if possible?

`rich` and `RichGeo_service` are for `EICrecon` and therefore has to be a plugin; `richgeo` should not be a plugin, since it is meant to be fully independent of `EICrecon`, and is actively used from the outside for `juggler` support and can be used for running `irt` PID standalone. However, after a long struggle and higher priorities I gave up and just made `richgeo` be another plugin, to be more stable against `cmake` config changes etc. (more of an issue in the past, hopefully).

**Comment by c-dilks** [comment]
> @c-dilks Our messages crossed. I don't see how this is relevant to IRT. In terms of CMake a working workaround for this case is:
> 
> ```diff
> diff --git a/src/services/geometry/rich/CMakeLists.txt b/src/services/geometry/rich/CMakeLists.txt
> index 30ca83d..2cd5729 100644
> --- a/src/services/geometry/rich/CMakeLists.txt
> +++ b/src/services/geometry/rich/CMakeLists.txt
> @@ -22,3 +22,5 @@ plugin_glob_all(${PLUGIN_NAME})
>  plugin_add_dd4hep(${PLUGIN_NAME})
>  plugin_add_irt(${PLUGIN_NAME})
>  plugin_add_acts(${PLUGIN_NAME})
> +
> +target_link_libraries(${PLUGIN_NAME}_plugin richgeo_plugin)
> ```
> 
> Also, this should not affect linux with its ld dynamic linker.

I am stumped enough on #398 to be desperate for any clues ;)
Anyway, I would very much appreciate any help on these issues

**Comment by veprbl** [comment]
If it's not a plugin, let's make it into a regular shared or static library for external use? Also, you say this functionality is used in Juggler, but latter doesn't depend on EICrecon. Do you mean that you synchronize the files? In that case, why not just change how you link rich plugin to just include those object files?
