### ISSUE TITLE
GetRefChild debug pollutes output

### ISSUE THREAD

**Issue by veprbl** [eic/EICrecon#485]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): main?
- Which version (or `HEAD` for the most recent on git): HEAD?
- Any specific OS or system where the issue occurs? linux
- Any special versions of ROOT or Geant4? no

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. Run reconstruction, look at the output

or look at logs in CI

1. https://github.com/eic/EICrecon/actions/runs/4170888923/jobs/7220477374

### Expected Result: (what do you expect when you execute the steps above)

Remove/hide this output or make it more clear to a regular user.

### Actual Result: (what do you get when you execute the steps above)

```
GetRefChild: Failed to find child with name: HcalEndcapPInsertHits Map contains 25 elements.
   0  B0ECalHits
   0  B0TrackerHits
   0  DIRCBarHits
   0  DRICHHits
   0  EcalBarrelSciGlassHits
   0  EcalEndcapNHits
   0  EcalEndcapPHits
   0  ForwardOffMTrackerHits
   0  ForwardRomanPotHits
   0  HcalBarrelHits
   0  HcalEndcapNHits
   0  HcalEndcapPHits
   0  LumiSpecCALHits
   0  LumiSpecTrackerHits
   0  MPGDBarrelHits
   0  MPGDDIRCHits
   0  MRICHHits
   0  SiBarrelHits
   0  TOFBarrelHits
   0  TOFEndcapHits
   0  TaggerTrackerHits
   0  TrackerEndcapHits
   0  VertexBarrelHits
   0  ZDCEcalHits
   0  ZDCHcalHits
```

**Comment by veprbl** [comment]
Somehow `grep GetRefChild` doesn't return anything for EICrecon

**Comment by veprbl** [comment]
Apparently it comes from DD4hep
https://github.com/AIDASoft/DD4hep/blob/84f2e45ec8a26efbfb6da07258be895310e652bf/DDCore/src/DetectorImp.cpp#L649

**Comment by veprbl** [comment]
Filed https://github.com/AIDASoft/DD4hep/issues/1102

But we should still figure out how to not ignore those exceptions in a loop.

**Comment by wdconinc** [comment]
One related issue could be that we don't throw these runtime errors up to jana2 anymore, https://github.com/eic/EICrecon/blob/2a3f2680d102d8babd7952ca5ed18c7245783b49/src/algorithms/calorimetry/CalorimeterHitDigi.cc. That means jana2 doesn't know to start treating the algorithm as bad and we get GetRefChild errors for every event.

**Comment by veprbl** [comment]
https://github.com/AIDASoft/DD4hep/pull/1106
cc @wdconinc

**Comment by veprbl** [comment]
Silencing the excessive output is an immediate issue for the upcoming production. The upstream PR above addresses that. The issue with exception handling in EICrecon would need to be filed and addressed separately.

**Comment by wdconinc** [comment]
huh
```
/usr/bin/patch: **** malformed patch at line 34:  
```
not sure what's wrong

**Comment by veprbl** [comment]
Could it be that you are missing a trailing newline?

**Comment by wdconinc** [comment]
That's what it seems like. I'm going through permutations and rediffing... On my phone...

**Comment by wdconinc** [comment]
I think this can be closed, right?

**Comment by veprbl** [comment]
Fixed in DD4hep
