### ISSUE TITLE
Reconstruction failures are not reported in exit code

### ISSUE THREAD

**Issue by veprbl** [eic/EICrecon#495]
### Environment: (where does this bug occur, have you tried other environments)
This is on CI

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. Make a change that breaks reconstruction: https://github.com/eic/EICrecon/actions/runs/4170791240/jobs/7220213032

### Expected Result: (what do you expect when you execute the steps above)

Red checkmark

### Actual Result: (what do you get when you execute the steps above)

A green checkmark on a job that produced a single event instead of a thousand.
https://github.com/eic/EICrecon/actions/runs/4170791240/jobs/7220213032

```output
+--------------------------+------------+--------+-----+---------+-------+--------+---------+-------------+
  |           Name           |   Status   |  Type  | Par | Threads | Chunk | Thresh | Pending |  Completed  |
  +--------------------------+------------+--------+-----+---------+-------+--------+---------+-------------+
  | sim_dis_10x100_minQ2=1000_arches.edm4hep.root | Finished   | Source |  F  |       0 |    40 |      - |       - |           1 |
  | processors               | Finished   | Sink   |  T  |       0 |     1 |     80 |       0 |           1 |
  +--------------------------+------------+--------+-----+---------+-------+--------+---------+-------------+
  +--------------------------+-------------+--------------+----------------+--------------+----------------+
  |           Name           | Avg latency | Inst latency | Queue latency  | Queue visits | Queue overhead | 
  |                          | [ms/event]  |  [ms/event]  |   [ms/visit]   |    [count]   |     [0..1]     | 
  +--------------------------+-------------+--------------+----------------+--------------+----------------+
  | sim_dis_10x100_minQ2=1000_arches.edm4hep.root |          58 |           58 |         0.0006 |            1 |       1.04e-05 |
  | processors               |    1.08e+04 |     1.08e+04 |         0.0066 |            1 |        6.1e-07 |
  +--------------------------+-------------+--------------+----------------+--------------+----------------+
  +----+----------------------+-------------+------------+-----------+----------------+------------------+
  | ID | Last arrow name      | Useful time | Retry time | Idle time | Scheduler time | Scheduler visits |
  |    |                      |     [ms]    |    [ms]    |    [ms]   |      [ms]      |     [count]      |
  +----+----------------------+-------------+------------+-----------+----------------+------------------+
  |  0 | idle                 |    1.08e+04 |      0.002 |         0 |         0.0008 |                2 |
  +----+----------------------+-------------+------------+-----------+----------------+------------------+
```

**Comment by veprbl** [comment]
Not clear if EICrecon fails to return a proper failure exit code, or CI manages to ignore it.

**Comment by wdconinc** [comment]
EICrecon returns failure exit codes and CI catches them in other cases, e.g. segfaults with backtrace in https://github.com/eic/EICrecon/actions/runs/4188047879/jobs/7258963632.

This is an issue of EICrecon not thinking this was a problem. So, indeed, @faustus123 @DraTeots why didn't EICrecon return a failing exit code here when it stopped processing due to a fatal exception in the first event?

**Comment by faustus123** [comment]
This was determined to be a fatal error by the `CalorimeterHitsMerger` factory which was calling `JApplication::Quit` without setting an exit code via a call to `JApplication::SetExitCode` ([see here](https://github.com/JeffersonLab/JANA2/blob/5d2f85e35db3e629df279de7d59282e39d330fad/src/libraries/JANA/JApplication.h#L77)). i.e. the factory was basically instructing JANA to exit cleanly without changing the exit code from the default value of '0'.

**Comment by wdconinc** [comment]
Is there a reason why your team ported all the instances of `return StatusCode::FAILURE` in juggler to this without setting a failure exit code?

**Comment by faustus123** [comment]
JANA does not support an init method returning a status code like Gaudi does. Thus, the only option of handling an "init failure" is to treat it as a fatal error. I believe messages are printed describing the error in these cases. Not setting the exit code was an oversight. Mainly due to debugging via manual runs as opposed to CI or job campaigns where having a proper exit code is much more critical and visible.

**Comment by wdconinc** [comment]
@DraTeots Can your TF go back and fix this everywhere?
