### ISSUE TITLE
Renaming of TPCHit in EDM4hep

### ISSUE THREAD

**Issue by jmcarcell** [eic/EICrecon#515]
This PR: https://github.com/key4hep/EDM4hep/pull/179 is going to be merged soon and it will rename one field that appears a few times in this repo:
```
src/utilities/podio_copy/podio_copy.cc
27:#include <edm4hep/TPCHitCollection.h>
292:    if( colltype=="edm4hep::TPCHit" ) return CopyCollectionT<edm4hep::TPCHit, edm4hep::TPCHitCollection>( store_in, store_out, name);

src/utilities/podio_read/podio_read.cc
27:#include <edm4hep/TPCHitCollection.h>
302:    if( colltype=="edm4hep::TPCHit" ) return CopyCollectionT<edm4hep::TPCHit, edm4hep::TPCHitCollection>( store_in, store_out, name);
```
The change (in this case, it's not the only one, see discussion and linked PRs in the EDM4hep PR) is easy to do, rename `TPCHit` to `RawTimeSeries` and for collections `TPCHitCollection` to `RawTimeSeriesCollection`. I open this issue in this repo but it's relevant for all repos that use this, which I haven't checked (`EDM4eic` seems to be unaffected).

**Comment by wdconinc** [comment]
Thanks a lot, @jmcarcell. We really appreciate the heads up! It seems that we will be relatively little affected by this, and you have identified the places where we will be affected.
