### ISSUE TITLE
Move to only static libraries or only shared libraries

### ISSUE THREAD

**Issue by veprbl** [eic/EICrecon#518]
Having several duplicates of the same translation units causes:
1. bloat in size
2. increases linking time
3. creates confusion about what links with what and when

This would probably solve #340 on the way.

**Comment by DraTeots** [comment]
I believe @faustus123 can explain why it is there, how it is beneficial and if we need to change it.

**Comment by faustus123** [comment]
IMHO we should place core services and common reconstruction pieces in shared libraries and more specialized code (e.g. monitoring certain benchmarking) in JANA plugins. We should probably steer clear of static libraries unless there is a specific case that motivates it. I mentioned this in my presentation on Dec. 7 of last year.

[https://indico.bnl.gov/event/17858/](https://indico.bnl.gov/event/17858/)

**Comment by faustus123** [comment]
We are currently working on revising how JANA deals with linking and loading plugins. One issue with the current system in both the JANA and EICrecon cmake configurations is that they add `JANA_LIB` to the plugins themselves. The core JANA library functions should come from the main executable (e.g. `eicrecon`) and having them in the plugins too is redundant. I believe this may have been what the OP was pointing to.

The quick solution is to add something like this:

~~~
target_compile_options( eicrecon PRIVATE -rdynamic )
~~~

to the [eicrecon CMakelists.txt](https://github.com/eic/EICrecon/blob/main/src/utilities/eicrecon/CMakeLists.txt) 

and to remove the JANA_LIB values from

[here](https://github.com/eic/EICrecon/blob/5f598b887d60eced640632ad3bbd9f24e74c1c8e/cmake/jana_plugin.cmake#L36) and [here](https://github.com/eic/EICrecon/blob/5f598b887d60eced640632ad3bbd9f24e74c1c8e/cmake/jana_plugin.cmake#L37)
and
[here](https://github.com/eic/EICrecon/blob/5f598b887d60eced640632ad3bbd9f24e74c1c8e/cmake/jana_plugin.cmake#L50) and [here](https://github.com/eic/EICrecon/blob/5f598b887d60eced640632ad3bbd9f24e74c1c8e/cmake/jana_plugin.cmake#L51)

There may be other places as well that need `JANA_LIB` removed.

At the moment, I am working on getting this implemented and working correctly in all places in the JANA source. I can work on updating `eicrecon` after the new version of JANA is released, but that may be 2-3 weeks (if all goes well). If someone else has time to update EICrecon and test the changes before then, then they should feel free to go ahead. Just note it here so I know it is being worked on and we don't duplicate effort.

**Comment by DraTeots** [comment]
Please, notify when it is done in JANA. We'll decide on assignee for the issue for EICrecon
