### ISSUE TITLE
cmake: `eicrecon -v` reports incorrect version

### ISSUE THREAD

**Issue by veprbl** [eic/EICrecon#523]
https://github.com/eic/EICrecon/blob/5f598b887d60eced640632ad3bbd9f24e74c1c8e/CMakeLists.txt#L31

Has to read from git tag or at least allow to specify a build version from a package manager.

**Comment by wdconinc** [comment]
This is 'easy' to solve when you can guarantee that you are building from a git clone, but that's not how we are installing most packages like EICrecon (but, notably, not EICrecon itself, right now) in the containers. We should probably just implement that for git clones (when `.git` exists). With some good example code here, it can propagate to other projects in EIC.

The canonical approach we use to install packages is to use a hashed* release tar ball (e.g. https://github.com/eic/EICrecon/archive/refs/tags/v0.6.2.tar.gz) so we can be sure the release hasn't changed from the time the packager verified it (retag a different commit with the same tag... like JANA2 has been known to do). I don't know a good solution to that part that doesn't impose the responsibility to set the version number on the packaging system and builder.

* yeah, I know that's fragile, and we were also affected by the github hash changes, https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/.

**Comment by veprbl** [comment]
git archive has a feature to bake some information about commits and tags into the archive, but it leads to irreproducible hashes. I'd recommend staying away from this.

Mechanisms like `SETUPTOOLS_SCM_PRETEND_VERSION` allow for decent fallback to use in packaging.
