### ISSUE TITLE
Failures on CI: `free(): invalid pointer`

### ISSUE THREAD

**Issue by veprbl** [eic/EICrecon#525]
EICrecon crashes at the end:
https://github.com/eic/EICrecon/actions/runs/4332231665/jobs/7564623572

**Comment by wdconinc** [comment]
Could this be related to what I posted a week ago, https://eic.cloud.mattermost.com/main/pl/yuwfomtdjbd3unjkopd5z8gkxh ? That referred to https://github.com/eic/EICrecon/actions/runs/4286005248/jobs/7469782762 which gives an error at the end as well, though not an invalid pointer on free. Already then it seemed primarily to happen for arches.

**Comment by DraTeots** [comment]
This one fails on particle gun with PI on arches. 

https://github.com/eic/EICrecon/actions/runs/4332231665/jobs/7564623572

I am trying to reproduce now

**Comment by wdconinc** [comment]
Even just `eicrecon -v` returns `free(): double free detected in tcache 2` in `eic-shell`.

**Comment by DraTeots** [comment]
I was able to reproduce it not only on docker but also on locally compiled setup. Everything works if JANA2 is switched back to v2.0.8

**Comment by wdconinc** [comment]
@DraTeots Can you fix this in EICrecon or identify what bugfix is needed in JANA? I'd prefer if @nathanwbrei continues to work on the PODIO support.

**Comment by DraTeots** [comment]
Just had a meeting where we planned it like this: @faustus123 will look into it on JANA2 side, I will try to fix it on EICrecon part (David has an idea which may help), @nathanwbrei will continue with PODIO

**Comment by DraTeots** [comment]
Both happened: 

1. CI works
2. JANA double free issue was traced and fixed https://github.com/JeffersonLab/JANA2/pull/205

**Comment by DraTeots** [comment]
But this recommendation has to be done: 

> @faustus123 Note that in order for this fix to work in external projects, they also need to be careful of ODR violations. Specifically, they will need to remove the linking of the JANA library to plugins and only link it in to their respective executables. The executables may also need to be compiled with -rdynamic.
