### ISSUE TITLE
Roman Pots reconstruction crashing at runtime

### ISSUE THREAD

**Issue by ajentsch** [eic/EICrecon#529]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released):
- Which version (or `HEAD` for the most recent on git):
- Any specific OS or system where the issue occurs?
- Any special versions of ROOT or Geant4?

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. checkout eicrecon branch "fix-roman-pots-reco"
2. run with any usable edm4eic ROOT file.

### Expected Result: (what do you expect when you execute the steps above)

Should produce reconstructed momentum vectors from Roman Pots matrix code.

### Actual Result: (what do you get when you execute the steps above)

SEG FAULT/ runtime error: see attached logfile.
[eicrecon_log_3_8_2023.log](https://github.com/eic/EICrecon/files/10923336/eicrecon_log_3_8_2023.log)

**Comment by DraTeots** [comment]
I believe this could be closed now. What happened - wrong plugin search directory was used because environment hasn't been set.
