### ISSUE TITLE
Use one string class for everything

### ISSUE THREAD

**Issue by c-dilks** [eic/EICrecon#531]
> We should use one string class for everything. If this is a collaboration, authorship doesn't grant ownership over the code.

_Originally posted by @veprbl in https://github.com/eic/EICrecon/pull/524#discussion_r1126921346_

**Comment by veprbl** [comment]
I'm not sure what this is about. The `grep -r TString .` gives nothing in the current codebase, just don't introduce it and it will be fine.

**Comment by c-dilks** [comment]
> I'm not sure what this is about.

This was your idea from discussions in #524. Please just close this issue with no PR if you no longer consider this to be useful.
