### ISSUE TITLE
need to be careful of ODR violations

### ISSUE THREAD

**Issue by veprbl** [eic/EICrecon#548]
But this recommendation has to be done: 

> @faustus123 Note that in order for this fix to work in external projects, they also need to be careful of ODR violations. Specifically, they will need to remove the linking of the JANA library to plugins and only link it in to their respective executables. The executables may also need to be compiled with -rdynamic.

_Originally posted by @DraTeots in https://github.com/eic/EICrecon/issues/525#issuecomment-1461048999_

**Comment by wdconinc** [comment]
Resolved in #1023
