### ISSUE TITLE
`// TODO: implement named geometry service?` in factories

### ISSUE THREAD

**Issue by veprbl** [eic/EICrecon#558]
In the current code, the `m_geoSvcName` is initialized with three possible values:
 - GeoSvc
 - ActsGeometryProvider
 - geoServiceName

The latter one seems bogus. From what it seems, it is simply not used:

https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/HCAL/CalorimeterHit_factory_HcalEndcapNRecHits.h#L65
https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/HCAL/RawCalorimeterHit_factory_HcalBarrelRawHits.h#L51
https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/HCAL/CalorimeterHit_factory_HcalEndcapPRecHits.h#L65
https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/HCAL/CalorimeterHit_factory_HcalEndcapPInsertRecHits.h#L65
https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/HCAL/RawCalorimeterHit_factory_HcalEndcapPRawHits.h#L51
https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/HCAL/CalorimeterHit_factory_HcalBarrelRecHits.h#L65
https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/HCAL/RawCalorimeterHit_factory_HcalEndcapNRawHits.h#L51
https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/HCAL/RawCalorimeterHit_factory_HcalEndcapPInsertRawHits.h#L51
https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/B0ECAL/CalorimeterHit_factory_B0ECalRecHits.h#L66
https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/B0ECAL/RawCalorimeterHit_factory_B0ECalRawHits.h#L52
https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/BEMC/CalorimeterHit_factory_EcalBarrelScFiRecHits.h#L70
https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/BEMC/CalorimeterHit_factory_EcalBarrelSciGlassRecHits.h#L60
https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/BEMC/RawCalorimeterHit_factory_EcalBarrelScFiRawHits.h#L51
https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/BEMC/RawCalorimeterHit_factory_EcalBarrelImagingRawHits.h#L49
https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/BEMC/CalorimeterHit_factory_EcalBarrelImagingRecHits.h#L52
https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/BEMC/RawCalorimeterHit_factory_EcalBarrelSciGlassRawHits.h#L51
https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/EEMC/CalorimeterHit_factory_EcalEndcapNRecHits.h#L67
https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/EEMC/CalorimeterHit_factory_EcalEndcapPRecHits.h#L66
https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/EEMC/RawCalorimeterHit_factory_EcalEndcapPRawHits.h#L51
https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/EEMC/RawCalorimeterHit_factory_EcalEndcapNRawHits.h#L52
https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/EEMC/RawCalorimeterHit_factory_EcalEndcapPInsertRawHits.h#L51
https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/EEMC/CalorimeterHit_factory_EcalEndcapPInsertRecHits.h#L66
https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/ZDC/CalorimeterHit_factory_ZDCEcalRecHits.h#L65
https://github.com/eic/EICrecon/blob/6ea1695d3cdaa2aef780882dfb0706923a1785d1/src/detectors/ZDC/RawCalorimeterHit_factory_ZDCEcalRawHits.h#L51

**Comment by wdconinc** [comment]
All unused geo services are
