### ISSUE TITLE
Detailed trajectory information writer

### ISSUE THREAD

**Issue by rahmans1** [eic/EICrecon#562]
**Is your feature request related to a problem? Please describe.**
A factory to write detailed trajectory information (Initial work done by Shyam). 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Simple-Shyam** [comment]
@rahmans1 I would like to point out. It's a plugin that will generate the branches corresponding to the variables listed on slide 10 of Shujie @ShujieL. She can also confirm it.
https://indico.bnl.gov/event/18213/contributions/73596/attachments/46172/78091/Track-recon-status-02_23_2023.pdf

The idea was once we activate this plugin during the reconstruction with eicrecon. The variables mentioned on slide 10 will be written in the output root file which is very important for the tracking studies.
The variables are on line 306 onward of the link below.

https://github.com/eic/EDM4eic/blob/main/edm4eic.yaml
