### ISSUE TITLE
CI `eicrecon --version` check fails from PRs from forks

### ISSUE THREAD

**Issue by c-dilks** [eic/EICrecon#567]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): any fork's branch with a PR targeting this main fork

### Steps to reproduce: (give a step by step account of how to trigger the bug)
Fork, branch, make a PR, check the CI. See https://github.com/eic/EICrecon/pull/566 for an example.

### Expected Result: (what do you expect when you execute the steps above)
CI `build` jobs pass

### Actual Result: (what do you get when you execute the steps above)
CI `build` jobs fail. `cmake` runs fine, but the version check
https://github.com/eic/EICrecon/blob/1f30d3b5e2aef6fdc9e7bccfe8b4e1228f63b551/.github/workflows/linux-eic-shell.yml#L62
Fails, since `eicrecon --version` returns `v0.0.0-unknown`

**Comment by wdconinc** [comment]
@veprbl Discussion on version number here.

**Comment by veprbl** [comment]
Maybe the rev doesn't correspond to any branch/tag when cloned from a fork
https://github.com/eic/EICrecon/actions/runs/4503316507/jobs/7926345872?pr=555#step:2:467

**Comment by c-dilks** [comment]
Let's at least clarify the error message: https://github.com/eic/EICrecon/pull/568

**Comment by veprbl** [comment]
Okay, I think I have a guess about what happened:
1. EICrecon was reporting a hardcoded version
2. The original PR was testing eicrecon from the container https://github.com/eic/EICrecon/pull/526/files#diff-1979202099e4ebc6d02b6dbd6ade89a6d9895896cd610bb3829b3b84f5239b38R62
3. Test passed despite github action checkout being shallow https://github.com/eic/EICrecon/actions/runs/4473203964/jobs/7860301460#step:7:111
4. New EICrecon got deployed to the container
5. Test started to fail
