### ISSUE TITLE
Use JMultiFactory for tracking output

### ISSUE THREAD

**Issue by DraTeots** [eic/EICrecon#579]
There is ParticlesFromTrackFitResult produced by TrackingParameters algorithms and factory which basically just a holder of multiple output types which are then separated into single collections. Now it can be done in one place using JMultiFactory

**Comment by kkauder** [comment]
@DraTeots Is this still open?

**Comment by wdconinc** [comment]
Everything is now using JChainMultifactory or JOmniFactory, including tracking.
