### ISSUE TITLE
Confusion of plugins between `eic-shell` container build and local build

### ISSUE THREAD

**Issue by c-dilks** [eic/EICrecon#588]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): `main`
- Which version (or `HEAD` for the most recent on git): `HEAD`
- Any specific OS or system where the issue occurs? `eic-shell`
- Any special versions of ROOT or Geant4? No

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. run `eic-shell` interactive container
2. build and install `EICrecon` locally, e.g., to `~/install`
3. source that local `EICrecon` build's environment with `source ~/install/bin/eicrecon-this.sh`
4. `echo $JANA_PLUGIN_PATH` returns:
```
~/install/lib/EICrecon/plugins:/usr/local/lib/EICrecon/plugins
```
5. try to fully disable the output of a particular collection, in particular, `ReconstructedChargedParticles` and `ReconstructedChargedParticlesAssociations`; one way is to comment out the corresponding lines from `tracking.cc`
6. rebuild locally, and run `eicrecon` (the above collections will be included by default)

### Expected Result: (what do you expect when you execute the steps above)
These collections to not appear, neither in the output nor in the `janadot` callgraph, since when commented out, there should be no knowledge of which factory is supposed to produce them.

### Actual Result: (what do you get when you execute the steps above)
They still appear. I suspect this is happening because since they cannot be found in the local `tracking.so` plugin, they are being found in the container's `tracking.so`. 

Workaround: when running with a local build, be sure only its plugins are included in `$JANA_PLUGIN_PATH` and that those from the container build are excluded.

**Comment by DraTeots** [comment]
> They still appear. I suspect this is happening because since they cannot be found in the local tracking.so plugin, they are being found in the container's tracking.so

Plugin mechanism works differently: it looks at the default plugins list which is overriden by `-Pplugins=...` flag if it is set. Then it loads corresponding `<plugin name>.so`. 

Please, add flag 

```
-Pjana:debug_plugin_loading=1
```

So that plugin full paths are printed. Something like: 

```
[DEBUG] JPluginLoader: Looking for './dd4hep.so' ....
[DEBUG] JPluginLoader: Failed to attach './dd4hep.so'
[DEBUG] JPluginLoader: Looking for '/home/romanov/eic/eicrecon/lib/EICrecon/plugins/dd4hep.so' ....
[DEBUG] JPluginLoader: Found!
[INFO] JPluginLoader: Initializing plugin "/home/romanov/eic/eicrecon/lib/EICrecon/plugins/dd4hep.so"
```

Whatever is written here is true, nothing else will be dynamically loaded if something is not found.

**Comment by c-dilks** [comment]
I've been running with `-Pjana:debug_plugin_loading=1`, but I can't remember if I checked it in my initial tests. I tried again today, and now suddenly I can no longer reproduce this issue!
