### ISSUE TITLE
Tool/option to list available types and collection names.

### ISSUE THREAD

**Issue by faustus123** [eic/EICrecon#61]
We need a tool to make it easy to list the available data types/name available in a eicrcon process. This should probably just be an option in eicrecon itself. It simply needs to loop over factories and print the data type and tag for each. This should be similar to the podio:print_type_table option in the podio plugin. The tool should actually be able to combine the lists of factories and of collections from the podio file.

The limitation here will be objects placed in the event with Insert() since those will not be known at program start up.

**Comment by nathanwbrei** [comment]
Here's a hint to help get you started: Take a look at JComponentManager::get_component_summary. All JANA components are registered in the JComponentManager after JApplication::Initialize() is called. The JComponentManager doesn't keep a pointer to factories directly (because JANA spins up multiple copies of each); instead, you have a set of JFactoryGenerators which populate a JFactorySet. Once the factory set is populated, you can query it using JFactorySet::Summarize(), or do what JFactorySet::Summarize does and iterate over all the factories to get the data you want.

**Comment by nathanwbrei** [comment]
@faustus123 If we always register the dummy factories with JANA the same way that GlueX does, we can query them just fine. Alternatively, we run JANA for a couple of events on the input file and then check to see what factories showed up.

**Comment by faustus123** [comment]
I assume you are referring to factories that are created merely as containers via JEvent::Insert() operations which don't happen until other factories are processed for an event.

I think having an option to run a few events would be good. Maybe a config parameter that is set to 0 by default, but the user can adjust?

**Comment by cissieAB** [comment]
Ask some dummy questions here: 
is this a tool to call JANA JComponentManager::get_component_summary and print out all the JFactory information?

If it is a tool to call JANA2, should the changes go to JANA repo instead of this one?

**Comment by nathanwbrei** [comment]
Not a silly question. JANA already prints this information out when you call JApplication::Init. My guess as to what David wants is to have a command-line option for the eicRecon executable that prints _only_ that table and then exits.

**Comment by DraTeots** [comment]
But it does only for activated plugins. What about scanning other plugins?

**Comment by faustus123** [comment]
We could have an option to scan all plugins in JANA_PLUGIN_PATH, but I would not make it the default. I would have it print the table of attached plugins and then a brief message saying something like:

Only attached plugins are shown
To scan all available plugins add "-Pprint_factories=scan_all"
To list all available plugins run with --list_plugins

My concern with scanning all of them is that there may be stale or conflicting plugins in the path they would never want to use.

Also, be sure to include the EICrecon_MY directory in the search path if it is set (see https://github.com/eic/EICrecon/blob/cd75a87b9847bca80fb3d9a84e0e65829a4b1466/src/utilities/eicrecon/eicrecon.cc#L35)

**Comment by cissieAB** [comment]
I just made a draft PR #94 that if given a cli option “--list_factories", the application will print the factories without processing the events (or, the true accurate description". But it will not print the collections messages. @faustus123 @nathanwbrei May I get some clues on how to handle option "Ppodio:print_type_table=1"? Thanks a lot!

```jug_xl> xmei@xmei-lpt-wifi:~/eic/dev/EICrecon$ eicrecon --list_factories -Ppodio:print_type_table=1 $EICTOPDIR/2022-09-04_pgun_e-_podio-0.15_edm4hep-0.6_0-30GeV_alldir_2k.edm4hep.root

[INFO] Creating pipe named "/tmp/jana_status" for status info.
[INFO] Setting signal handlers
[INFO] JPluginLoader: Initializing plugin "/home/xmei/eic/dev/EICrecon/lib/EICrecon/plugins/podio.so"
[INFO] JPluginLoader: Initializing plugin "/home/xmei/eic/dev/EICrecon/lib/EICrecon/plugins/dd4hep.so"
[INFO] JPluginLoader: Initializing plugin "/home/xmei/eic/dev/EICrecon/lib/EICrecon/plugins/log.so"
[INFO] JPluginLoader: Initializing plugin "/home/xmei/eic/dev/EICrecon/lib/EICrecon/plugins/rootfile.so"
[INFO] JPluginLoader: Initializing plugin "/home/xmei/eic/dev/EICrecon/lib/EICrecon/plugins/BEMC.so"
[INFO] JPluginLoader: Initializing plugin "/home/xmei/eic/dev/EICrecon/lib/EICrecon/plugins/EEMC.so"
[INFO] JArrowProcessingController: NUMA Configuration

  Affinity strategy: compute-bound (favor fewer hyperthreads)
  Locality strategy: global
  Location count: 1
  +--------+----------+-------+--------+-----------+--------+
  | worker | location |  cpu  |  core  | numa node | socket |
  +--------+----------+-------+--------+-----------+--------+
  |      0 |        0 |     0 |      0 |         0 |      0 |
  |      1 |        0 |     1 |      1 |         0 |      0 |
  |      2 |        0 |     2 |      2 |         0 |      0 |
  |      3 |        0 |     3 |      3 |         0 |      0 |
  |      4 |        0 |     4 |      4 |         0 |      0 |
  |      5 |        0 |     5 |      5 |         0 |      0 |
  |      6 |        0 |     6 |      6 |         0 |      0 |
  |      7 |        0 |     7 |      7 |         0 |      0 |
  |      8 |        0 |     8 |      0 |         0 |      0 |
  |      9 |        0 |     9 |      1 |         0 |      0 |
  |     10 |        0 |    10 |      2 |         0 |      0 |
  |     11 |        0 |    11 |      3 |         0 |      0 |
  |     12 |        0 |    12 |      4 |         0 |      0 |
  |     13 |        0 |    13 |      5 |         0 |      0 |
  |     14 |        0 |    14 |      6 |         0 |      0 |
  |     15 |        0 |    15 |      7 |         0 |      0 |
  +--------+----------+-------+--------+-----------+--------+


************** List all the factories ************

Plugin, Object name, Tag
BEMC.so, BEMCRawCalorimeterHit, 
BEMC.so, BEMCRawCalorimeterHit, utility
EEMC.so, eicd::ProtoCluster, EcalEndcapNIslandProtoClusters
EEMC.so, eicd::CalorimeterHit, EcalEndcapNRecHits
EEMC.so, edm4hep::RawCalorimeterHit, EcalEndcapNRawHits

**************************************************

[INFO] Closing Event Source for /home/xmei/eic/dev/2022-09-04_pgun_e-_podio-0.15_edm4hep-0.6_0-30GeV_alldir_2k.edm4hep.root
```
