### ISSUE TITLE
Make sure file headers are correctly transferred and all credits are saved

### ISSUE THREAD

**Issue by DraTeots** [eic/EICrecon#65]

**Comment by DraTeots** [comment]
Will be checking it

**Comment by wdconinc** [comment]
Not my job.

**Comment by DraTeots** [comment]
> Not my job.

Just to be clear. I'm not suggesting you to sit and fix headers but rather make sure in the end, that everything is correct and e.g. credits to your inputs are labelled/transferred correctly.

**Comment by DraTeots** [comment]
Said done in corresponding PR  #183
