### ISSUE TITLE
eicrecon-gcc-gun-EcalLumiSpec test is broken on main

### ISSUE THREAD

**Issue by veprbl** [eic/EICrecon#652]
https://github.com/eic/EICrecon/actions/runs/4888399445/jobs/8726255033#step:5:496
```
[JEventProcessorPODIO] [error] Omitting PODIO collection 'EcalLumiSpecClusters' due to exception: JFactoryPodioT: Unable to add collection to frame as frame is missing!.
```

**Comment by nathanwbrei** [comment]
This looks a lot like issue #631. I can help you with this if you need it ASAP

**Comment by nathanwbrei** [comment]
There's a "good" fix in PR #636, but that's held up by other crashes I haven't had the chance to debug. There are several levels of quick fixes available though

**Comment by dhevang** [comment]
Indeed, looks like the same thing as #631. If a good fix could be available in a week time scale, I would wait for that.
Otherwise, would you just suggest to include EcalLumiSpecClusterAssociations in the podio:output_include_collections as per #631 ?

**Comment by nathanwbrei** [comment]
> 

Go ahead and see if adding it fixes the problem. If not, I'll jump in

**Comment by veprbl** [comment]
Looks like #653 fixes it. I'm so confused right now.

**Comment by nathanwbrei** [comment]
I can explain, but it's going to a long unpleasant explanation and the only meaningful takeaway is that using event->Insert() in this context is bad. If this makes the bug go away for now, just merge it, and I'll make a note to circle back and fix the collection name as part of PR #636.

**Comment by nathanwbrei** [comment]
Another, slightly better fix is to go to `github/workflows/linux-eic-shell.yml`, and change line 319 so that `-Ppodio:output_include_collections=EcalLumiSpecRawHits,EcalLumiSpecRecHits,EcalLumiSpecClusters` becomes -Ppodio:output_include_collections=EcalLumiSpecRawHits,EcalLumiSpecRecHits,EcalLumiSpecClusters,EcalLumiSpecClusterAssociations`.

**Comment by veprbl** [comment]
> I can explain, but it's going to a long unpleasant explanation and the only meaningful takeaway is that using event->Insert() in this context is bad. If this makes the bug go away for now, just merge it, and I'll make a note to circle back and fix the collection name as part of PR #636.

What is so special about EcalLumiSpecClusterAssociations compared to EcalLumiSpecCluster***s***Associations?

**Comment by veprbl** [comment]
And why does it not matter for other factories that use "...ClusterAssociations"?

**Comment by dhevang** [comment]
I added the EcalLumiSpecClusterAssociations.  It prevented the error.  I do see clusters in eicrecon_rec_e_EcalLumiSpec_ip6_extended.edm4eic.root.  
However, I ran 100 events with 1 electron per event always hitting the sample place and I only see 76 clusters.
It should be much closer to 100.  Not sure what's causing this.

**Comment by veprbl** [comment]
@dhevang Have you checked the ddsim output?

**Comment by dhevang** [comment]
Yes, I see 100 generated electrons in total in the MCParticles folder.  The LumiSpecCALHits has 5809 hits.  This looks fine.
