### ISSUE TITLE
return smart pointers, not `new` raw pointers

### ISSUE THREAD

**Issue by c-dilks** [eic/EICrecon#661]
**Is your feature request related to a problem? Please describe.**
Returning `new` raw pointers from a function has the possibility of causing memory leaks.

**Describe the solution you'd like**
Return `unique_ptr` or `shared_ptr`. The following files contain the string `return new`:
- [x] src/algorithms/trk_chain_example/v3/SimTrackerHitDigi.h, https://github.com/eic/EICrecon/commit/b09ea2af6d34d18b33cc79a81f0f68c90ad21a7d
- [x] src/algorithms/tracking/TrackPropagation.cc (addressed by #656)
- [x] src/algorithms/reco/MC2SmearedParticle.cc, https://github.com/eic/EICrecon/commit/433985e27bcb24b3dc957315c4d30d2d533034d5
- [x] src/algorithms/tracking/TrackerHitReconstruction.cc, https://github.com/eic/EICrecon/pull/840
- [x] src/algorithms/calorimetry/CalorimeterClusterRecoCoG.cc, https://github.com/eic/EICrecon/commit/22c046a45496fcb91d303c497458eb99dd0b7965

**Comment by wdconinc** [comment]
Although all boxes are checked, we should still remove the return new at https://github.com/eic/EICrecon/blob/1ed357a478138da27585a006a9b667eed86f5a0d/src/algorithms/calorimetry/CalorimeterClusterRecoCoG.cc#L294 by converting to a std::optional
