### ISSUE TITLE
Allow collections written to an output file to be reread to continue analysis.

### ISSUE THREAD

**Issue by simonge** [eic/EICrecon#667]
Currently EICrecon output files, generally, cannot be reread by EICrecon to add to an analysis.

There appear to be at least 2 issues (maybe more but I can't get past the second one).

1. EICrecon requires the EventHeader collection to be present, this is currently not kept in the default list.
2. Trying to read a new collection which wasn't present in the original epic output file returns e.g.

```
- JFactoryPodioT<edm4eic::RawTrackerHit>* JEvent::InsertCollectionAlreadyInFrame<edm4eic::RawTrackerHit>(PodioTypeMap<edm4eic::RawTrackerHit>::collection_t const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (0x7f9e563d4695)
    - void InsertingVisitor::operator()<edm4eic::RawTrackerHitCollection>(edm4eic::RawTrackerHitCollection const&) (0x7f9e563bde3a)
     - VisitPodioCollection<InsertingVisitor>::operator()(InsertingVisitor&, podio::CollectionBase const&) (0x7f9e563b183a)
      - JEventSourcePODIO::GetEvent(std::shared_ptr<JEvent>) (0x7f9e563a847f)
       - JEventSource::DoNext(std::shared_ptr<JEvent>) (0x7f9e602d3c43)
        - JEventSourceArrow::execute(JArrowMetrics&, unsigned long) (0x7f9e602dc265)
         - JWorker::loop() (0x7f9e602e14d7)
          - /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x7f9e5fc564a3)
           - /lib/x86_64-linux-gnu/libc.so.6 (0x7f9e5fa07fd4)
            - /lib/x86_64-linux-gnu/libc.so.6 (0x7f9e5fa885bc)
```

My primary intention for this is training and testing neural networks faster, but other uses where only a subset of the data is needed to test different approaches quickly without having to run through all of the collections will be faster too. I'm sure there are other useful reasons to implement this as well.

**Comment by wdconinc** [comment]
Was this the error you were encountering here? https://github.com/eic/EICrecon/actions/runs/6285667201/job/17068353375#step:7:509
```
[FATAL] Detected exception in worker! Re-throwing on main thread.
----------------------------------------------------------
Exception: Bad event headers: Entry 0 contains 0 items, but 1 expected.
  Plugin:         podio
  Component:      JEventSourcePODIO
```

**Comment by simonge** [comment]
Looks correct for the first part of the issue. From the checks on the update it looks like the second issue might have resolved itself in the meantime? It would be good to add EventHeader to the output file independently of being specified on the podio:output_include_collections list if possible

**Comment by wdconinc** [comment]
> It would be good to add EventHeader to the output file independently of being specified on the podio:output_include_collections list if possible

Added to the PR just now.

**Comment by wdconinc** [comment]
If you can, please test whether the PR fixes what you were trying to do. There are some quality of life issues left with this, chiefly you have to specify everything on the command line. I'm not sure what a good scalable approach is towards separation in a different way, but likely it requires a solution to the configuration management question first.

**Comment by simonge** [comment]
I can have a look and test it with some different types/breaks in the reconstruction. It doesn't look like there's anything in the PR which should directly effect the issue, maybe some of the dependency updates have helped.

**Comment by simonge** [comment]
I think part 2 of the issue relates to the ambiguities if you'd like to write a collection out which is in your input file but also can be constructed in the code, for example adding EcalBarrelImagingRawHits to the output of the second step in the workflow. The fix would be to check the file to see if it contains the requested collection first and skip attempting to reproduce it. I can see this getting quite messy if for instance some intermediate reconstruction is requested in the second output but not provided in the first.
Running into strange library problems today which means I haven't managed to test/confirm this how I'd intended.
