### ISSUE TITLE
The local maxima of the island clustering

### ISSUE THREAD

**Issue by johnny8266** [eic/EICrecon#680]
https://github.com/eic/EICrecon/blob/1aa1e468a50f17f32a48704b0bc311fa16aa883e/src/algorithms/calorimetry/CalorimeterIslandCluster.h#L176C1-L209

I currently work on the pi0 study on NEEMC by the island clustering. When the 2 cluster are well separated, there is no problem for the clustering. 
However, the islandclustering always return 1 local maximum when the 2 clusters are partially overlapped but the local maxima are well separated. I guess the problem is from L.176. I don't know what the global means in the if() argument. It seems always true, so the function, from L.189 to L.212, for searching the multiple local maxima is never executed.

**Comment by veprbl** [comment]
The log messages are a bit misleading. If `m_splitCluster=false`, it say that only one maximum is found despite two or more present in the event.

**Comment by veprbl** [comment]
Btw, `global = !m_splitCluster`

**Comment by johnny8266** [comment]
Thanks for elaboration.
I gave it a quick try by replacing the "global" with "false", then it can find the multiple local maxima. But I get another error message after it process 1st event:

[JEventProcessorPODIO] [error] Omitting PODIO collection 'EcalEndcapNClusters' due to exception: bad_function_call.
 
And no data is saved in the podio file. I am wondering is this error triggered by calling the function "is_neighbour()"?

**Comment by veprbl** [comment]
#638 should fix that

**Comment by johnny8266** [comment]
Got it. #638 is not merged into the main, right?

**Comment by veprbl** [comment]
Now it is.

**Comment by johnny8266** [comment]
Thanks it works well!
