### ISSUE TITLE
IRT: offset of reconstructed Cherenkov angle

### ISSUE THREAD

**Issue by c-dilks** [eic/EICrecon#693]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): currently `irt-algo` and `irt-algo-stable`; `main` when initial version of algorithm `IrtCherenkovParticleID` is merged

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. Run `IrtCherenkovParticleID` and check the resulting Cherenkov angle residuals

### Expected Result: (what do you expect when you execute the steps above)
Residual centered around zero.

### Actual Result: (what do you get when you execute the steps above)
Residual center is off by ~6 mrad.

**Comment by chchatte92** [comment]
Hi Chris, the saturated Cherenkov angles are around 37 mrad. However, this  should be around 39 mrad (our ATHENA reference), the ATHENA values were round 0.5 mrad lower compared to the beam test results of Marco et al. They obtained around 40 mrad.
