### ISSUE TITLE
Source eicrecon-this.sh in the linux-eic-shell.yml workflow

### ISSUE THREAD

**Issue by simonge** [eic/EICrecon#703]
**Is your feature request related to a problem? Please describe.**
I would like to be able to give a default, relative path to a file (xml/dat) containing weights for a neural network. This is currently possible from when the environment variable EICrecon_ROOT has been set but this is not included in the github workflow so won't be possible to merge.

**Describe the solution you'd like**
Add "source eicrecon-this.sh" to the workflow somwhere described in linux-eic-shell.yml

**Describe alternatives you've considered**
Including the weight files in the epic repository which is already sourced.

**Additional context**
This might break other peoples workflow as currently it doesn't need to be sourced to run the code.

**Comment by veprbl** [comment]
We already require a `JANA_PLUGIN_PATH`, it's not unfathomable that we can require EICRECON_DATA_PATH or something like that. If you have a code ready to submit, we can sort out the CI issues in a PR.

**Comment by simonge** [comment]
This is the related PR
https://github.com/eic/EICrecon/pull/675

There are still a number of other issues I've been working on related to it in the meantime
