### ISSUE TITLE
Crashes at `edm4eic::ReconstructedParticle::~ReconstructedParticle()`

### ISSUE THREAD

**Issue by veprbl** [eic/EICrecon#704]
Crashes on main CI:

```output
Thread model: pthreads
140557365225152: 
       `- JSignalHandler::handle_sigsegv(int, siginfo_t*, void*) (0x7fd62430a296)
        `- /lib/x86_64-linux-gnu/libc.so.6 (0x7fd623df7f90)
         `- edm4eic::ReconstructedParticle::~ReconstructedParticle() (0x7fd621039238)
          `- eicrecon::JFactoryPodioT<edm4eic::ReconstructedParticle>::ClearData() (0x7fd62048f7a0)
           `- JFactorySet::Release() (0x7fd624256eb2)
            `- JEventSourceArrow::execute(JArrowMetrics&, unsigned long) (0x7fd62427ddb8)
             `- JWorker::loop() (0x7fd6242834d7)
              `- /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x7fd6240914a3)
               `- /lib/x86_64-linux-gnu/libc.so.6 (0x7fd623e44fd4)
                `- /lib/x86_64-linux-gnu/libc.so.6 (0x7fd623ec55bc)
````

https://github.com/eic/EICrecon/actions/runs/5171956733/jobs/9316138182

Occur since innocent-looking fd2b6e976294d991f425c1a0691b316093ab3e14

**Comment by veprbl** [comment]
Since this only happens on main, will try to clear caches an rerun the actions

**Comment by veprbl** [comment]
That cleared out the issues. @wdconinc Are you seeing this locally? Maybe, there was some recent container rebuild?

**Comment by wdconinc** [comment]
No changes in container for last two weeks, https://eicweb.phy.anl.gov/containers/eic_container/-/commits/master?ref_type=heads. Not sure what this is. Maybe we need to add the date to the cache key to force at least a rerun once per day?

**Comment by veprbl** [comment]
When deleting the ccache caches, I've noticed, there were two timestamped sets. So I thought there was already a key for the date.

**Comment by veprbl** [comment]
No actionable items, for now, at least.
