### ISSUE TITLE
behavior change of `JChainMultifactoryT::GetPrefix()` breaks PID algorithm configuration

### ISSUE THREAD

**Issue by c-dilks** [eic/EICrecon#732]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): `main`
- Which version (or `HEAD` for the most recent on git):
- Any specific OS or system where the issue occurs?
- Any special versions of ROOT or Geant4?

### Steps to reproduce: (give a step by step account of how to trigger the bug)

PR #666 included a bug fix in `JChainMultiFactoryT` which allows `GetPrefix()` to return `plugin_name:tag_name`; previously the return was `:tag_name`.

While this is a welcome change, this should have been done in a separate PR.

This is a breaking change for PID factories: try to override a configuration parameter for any of the following PID factories, using the `-Pplugin:tag:param=value` option of `eicrecon`:
```
src/global/digi/PhotoMultiplierHitDigi_factory.cc
src/global/pid/IrtCherenkovParticleID_factory.cc
src/global/pid/RichTrack_factory.cc
```

These factories assume the previous behavior of `GetPrefix()` which returns `:tag_name`.

### Expected Result: (what do you expect when you execute the steps above)
Parameter defaults overriden

### Actual Result: (what do you get when you execute the steps above)
Parameter remains default and is not overridden

**Comment by c-dilks** [comment]
Additional comments:
- globally impacting changes should always be done in a separate PR, and never buried as part of an unrelated PR
- factory boilerplate seems a bit fragile and prone to hidden mistakes; consider unit testing factories

**Comment by veprbl** [comment]
The change in question was tested by comparing `pi_{arches,brycecanyon}_flags.json` before and after. Looking now, I don't see `DRICH` flags even listed.

But yes, separate PR was the correct way to allow for a potentially better review.

**Comment by c-dilks** [comment]
> Looking now, I don't see `DRICH` flags even listed.

Likely because `DRICH` output collections are not included by default. One needs to run including all possible collections, even those that are used but not kept by default.

**Comment by veprbl** [comment]
Can you turn stuff on for CI? We can't test what we don't run.

**Comment by c-dilks** [comment]
It would have to be a separate job (see `eicrecon-gun-EcalLumiSpec`), since there are a few outstanding issues I would like to see resolved before enabling dRICH PID in default production.
