### ISSUE TITLE
Segment top-level README.md

### ISSUE THREAD

**Issue by faustus123** [eic/EICrecon#74]

**Comment by faustus123** [comment]
The top-level README.md file contains a lot of things and needs to be broken up into smaller pieces with links. This will allow easier navigation. The documentation will eventually need to be moved to someplace else (e.g. Jekyll) as discussed in the [Software Documentation decision](https://docs.google.com/document/d/1r_emjVz4aqiy93Hu7US9mewnd5NpnFyEQfQuH2U-WhU/edit). This will be entered as a separate task.

The current instructions on building all packages manually need to be moved to a special section that is clearly marked as a non-recommended way of doing this. The top of the README should instead have brief instructions for using eic-shell and a link to the tutorial page here: [https://eic.github.io/tutorial-setting-up-environment/](https://eic.github.io/tutorial-setting-up-environment/)

This can really be done by anyone with little to no knowledge of the EICrecon software stack itself.

**Comment by cissieAB** [comment]
A person "with little to no knowledge of the EICrecon software stack" sounds like me 🥲 
I can try building with maximum default eic-shell softwares. Some versions are different, but I guess it would not influence much.

**Comment by DraTeots** [comment]
While there is no official documentation engine (like Jekyll) I would propose to create doc folder and put markdown files there. I'm actually write this because it is a bit inconvenient to work with all those mermaid diagrams in one issue, so I would be glad to see the folder and introduce the change.

**Comment by cissieAB** [comment]
@DraTeots I just merged #111 to address this problem. 
A `docs` folder is created. Please add the contents you would like to introduce~
