### ISSUE TITLE
LFHCal between 80% and 90% of reconstruction time consumption

### ISSUE THREAD

**Issue by wdconinc** [eic/EICrecon#782]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): `main`
- Which version (or `HEAD` for the most recent on git): `HEAD`
- Any specific OS or system where the issue occurs? `eic-shell`
- Any special versions of ROOT or Geant4? no

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. Pick latest `main` branch at https://github.com/eic/EICrecon/actions?query=branch%3Amain+ (currently https://github.com/eic/EICrecon/actions/runs/5575953696)
2. Download `rec_dis_18x275_minQ2=1000_brycecanyon.dot` (currently https://github.com/eic/EICrecon/suites/14350109589/artifacts/808204419)
3. Unzip artifact
4. Filter zeros with `sed -i 's|0.0%"]|0.0%", penwidth=0]|g' jana.dot`
5. Convert to svg with `dot -Tsvg jana.dot > jana.svg`
6. Find the LFHCAL branch (which should be easily visible

See here:
![jana](https://github.com/eic/EICrecon/assets/4656391/5a840ceb-134a-4557-a2aa-884505e53994)

### Expected Result: (what do you expect when you execute the steps above)
Pareto principle: 80% of time spent in 20% of algorithms.

### Actual Result: (what do you get when you execute the steps above)
Over 80% of time is spent in LFHCAL alone.

**Comment by wdconinc** [comment]
This is all in the factory that creates `edm4eic::ProtoCluster:LFHCALIslandProtoClusters`.

**Comment by veprbl** [comment]
I suspect the implementation of the adjacencyMatrix is the culprit. I was originally investigating a possibility to use cling instead of CLHEP one from DD4hep. The main issue that there doesn't seem to be a way to instantiate an additional TInterpreter's to have them thread-local.

**Comment by wdconinc** [comment]
https://github.com/eic/EICrecon/blob/main/src/detectors/FHCAL/ProtoCluster_factory_LFHCALIslandProtoClusters.h#L52-L66 yeah :-D I didn't know that had grown so much.

**Comment by veprbl** [comment]
It could be just the O(N^2) due to combinatorics in the number of hits.

I bet we could cut the time in half by replacing this line with `break;`:
https://github.com/eic/EICrecon/blob/22247b4c3cd1d5821bfc96c18d142aec56886798/src/algorithms/calorimetry/CalorimeterIslandCluster.h#L203

**Comment by wdconinc** [comment]
If this is stable, could we pass a `std::function` from the factory and only defer to the evaluator when it is specified and different from the default?

**Comment by veprbl** [comment]
The evaluator path is just another possible value for the `std::function`.

**Comment by veprbl** [comment]
In fact, earlier today I was documenting that we should ditch all hardcoded functions in favor of evaluator: #781

**Comment by veprbl** [comment]
Or you mean pass pointer to function from cling? I think that's the only sensible way, yes.

**Comment by wdconinc** [comment]
This is all just algebraic operations, right? `+`, `-`, `*`, `==`, `&&`, `||`. Has no one ever written a 'simple' RPN parser that puts this into a computational graph? Isn't that what all the ML frameworks do anyway? Alternatively, isn't this in some sense a decision tree?
