### ISSUE TITLE
eicrecon default plugin list

### ISSUE THREAD

**Issue by faustus123** [eic/EICrecon#90]
eicrecon currently adds a set of default plugins by having a line calling AddPlugin for each. This list should be placed into a vector so it can be listed and manipulated with command line options. The command line options should include the following functionality:

- list default plugins
- do not attach default plugins
- exclude these from the list of default plugins to attach

No need to to have an option to add to the default list since -Pplugins=... already handles that functionality.

**Comment by cissieAB** [comment]
I see  L37-L46 list many plugins. Are they default plugins?

https://github.com/cissieAB/EICrecon/blob/main/src/utilities/eicrecon/eicrecon.cc#L37-L46

**Comment by cissieAB** [comment]
Referring to https://github.com/eic/EICrecon/issues/61#issuecomment-1239329595, we need

- "-list_default_plugins": list the default plugins now represented by [L37-L46](https://github.com/cissieAB/EICrecon/blob/main/src/utilities/eicrecon/eicrecon.cc#L37-L46);

- "--list_all_plugins": list all available plugins at $JANA_PLUGIN_PATH and $EICrecon_MY;

Do we need "--list_active_plugins" to list default_plugins+Pplugins-exclude_plugins? (Do not know the difficulty)

**Comment by faustus123** [comment]
>I see [L37-L46](https://github.com/cissieAB/EICrecon/blob/main/src/utilities/eicrecon/eicrecon.cc#L37-L46) list many plugins. Are they default plugins?

Yes, those are what I'm calling "default" plugins.

>I can start with "--list_default_plugins".
Since "-L" is already occupied by "--list_factories", is there any for-short letter you have in mind?
Maybe here we don't need a short version. "--list_default_plugins" is sufficient.

>Does that mean we do not want any of the [L37-L46](https://github.com/cissieAB/EICrecon/blob/main/src/utilities/eicrecon/eicrecon.cc#L37-L46)? Instead, we solely get plugins to add with the cli option "-Pplugins=..." and $EICrecon_MY?
Yes.

>Such as "--ex_plugins=${exclude_list}"? And then it will add everything in the default list (add those from -Pplugins) but not ${exclude_list}?
Right. I just want some way for them to modify the list of plugins at run time. 

>"--list_all_plugins": list all available plugins at $JANA_PLUGIN_PATH and $EICrecon_MY;

I would probably call it "--list_available_plugins"

>Do we need "--list_active_plugins" to list default_plugins+Pplugins-exclude_plugins? (Do not know the difficulty)
We probably do not need this.

**Comment by cissieAB** [comment]
@faustus123 @nathanwbrei  May I know which default plugins can be safely ignored?

Now I will got lots of troubles when I play with "-Pplugins_to_ignore" (shown in the "-c" option).
