### ISSUE TITLE
Create templated MergerFactory

### ISSUE THREAD

**Issue by simonge** [eic/EICrecon#917]
Merging collections of the same type from different sources occurs in multiple places throughout the code, currently a new factory and algorithm needs to be written for each type.

e.g.
https://github.com/eic/EICrecon/blob/main/src/factories/tracking/TrackerHitCollector_factory.cc
https://github.com/eic/EICrecon/blob/main/src/global/pid/MergeTrack_factory.cc
https://github.com/eic/EICrecon/blob/266-integrate-lowq2-tagger-reconstruction/src/factories/tracking/TrackerTrajectoryCollector_factory.h

**Describe the solution you'd like**
A single factory definition which takes a vector of collection names and outputs a merged collection.

**Describe alternatives you've considered**
Rewrite the same code for different collections each time

**Comment by wdconinc** [comment]
There are a bunch of other 'meta' factories that we anticipate needing, in particular filters with a predicate.
