### ISSUE TITLE
Track{Projector,Propagation}: investigate why we are unable to access ACTS surface id

### ISSUE THREAD

**Issue by veprbl** [eic/EICrecon#930]
https://github.com/eic/EICrecon/blob/e5f0a9df377a9f1f43a1addb42d6bb3712f281ac/src/algorithms/tracking/TrackProjector.cc#L151

https://github.com/eic/EICrecon/blob/e5f0a9df377a9f1f43a1addb42d6bb3712f281ac/src/algorithms/tracking/TrackPropagation.cc#L294

Read access fails under ASAN, write access causes segfault. Needs investigation.

See also #862

**Comment by wdconinc** [comment]
I can't reproduce this locally (clang, clang++, Debug, ASAN + UBSAN). Is this still an issue for you? Maybe the ODR violation or memory leak fixes addressed this?

I'm going to create a branch from this PR to see if maybe CI has trouble with it.
